### ISSUE TITLE
Hangs on import

### ISSUE THREAD

**Issue by tbardouille** [jonescompneurolab/hnn-core#106]
Hi there,

After installing hnn-core on my Mac, as per instructions in the README.rst file, python hangs (for several hours!) when I try to import hnn_core. Do I need a certain version of Anaconda (e.g., 2 or 3) for this to work? 

See standard output below:
$ python
Python 3.6.8 |Anaconda, Inc.| (default, Dec 29 2018, 19:04:46) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import hnn_core

**Comment by jasmainak** [comment]
uhmm ... this shouldn't happen. I am using a Mac as well. Anaconda 3 should be fine. Are you able to import `neuron`? E.g., if you do:

```py
>>> from neuron import h
```

does that work?

**Comment by tbardouille** [comment]
Hi Jas,

Yes, you're correct that this shouldn't happen. In fact, it has now stopped happening! :)

I restarted my computer, and that seemed to resolve the issue. Maybe I missed a step in the instructions.

Thank you!
Tim.

**Comment by jasmainak** [comment]
Excellent, good to know that!! Restarting always works ;-)

**Comment by tbardouille** [comment]
Classic IT Crowd. “Hello. IT. Have you tried turning it off and on?”
