### ISSUE TITLE
Replicate periodic evoked inputs with rhythmic inputs

### ISSUE THREAD

**Issue by blakecaldwell** [jonescompneurolab/hnn-core#114]
Moving this to hnn-core from [hnn](https://github.com/jonescompneurolab/hnn/)

From @rythorpe in https://github.com/jonescompneurolab/hnn/issues/208

> I currently have a param file with evoked inputs that have periodic spacing. My goal is to replicate the simulation with only rhythmic inputs, however, there seems to be a discrepancy in how synaptic weights are assigned for evoked vs. rhythmic inputs. The following screenshots demonstrate this issue and their corresponding param files are attached. Note that, according to the param files, the synaptic conductancies for proximal and distal inputs are congruent across simulations.

**Comment by jasmainak** [comment]
I just transferred the original issue. Closing this in favor of #115
