### ISSUE TITLE
Replicate periodic evoked inputs with rhythmic inputs

### ISSUE THREAD

**Issue by rythorpe** [jonescompneurolab/hnn-core#115]
I currently have a param file with evoked inputs that have periodic spacing. My goal is to replicate the simulation with only rhythmic inputs, however, there seems to be a discrepancy in how synaptic weights are assigned for evoked vs. rhythmic inputs. The following screenshots demonstrate this issue and their corresponding param files are attached. Note that, according to the param files, the synaptic conductancies for proximal and distal inputs are congruent across simulations.
![Screenshot from 2020-04-30 20-36-46](https://user-images.githubusercontent.com/20212206/80773238-4e306000-8b27-11ea-9c4f-23b3a3c86120.png)
![Screenshot from 2020-04-30 20-29-04](https://user-images.githubusercontent.com/20212206/80773310-8a63c080-8b27-11ea-86bb-35b287b70346.png)

I realize that there is a difference in how jitter is applied to individual evoked inputs vs. a series of rhythmic inputs; however, the fact that the simulations above produce dipoles that are different by an order of magnitude is confusing.

[param_files.zip](https://github.com/jonescompneurolab/hnn/files/4562140/param_files.zip)

**Comment by jasmainak** [comment]
> I thought the gaussian falloff was for local network connection weights but that synchronous evoked inputs targeted all relevant cells (according to their type) at the same time and same strength. Is that not correct?

The gaussian fall-off is controlled by the "lamtha" parameter. For rhythmic inputs, it seems to be [set at 100](https://github.com/jonescompneurolab/hnn-core/blob/master/hnn_core/params.py#L311) and for evoked inputs, it's [set at 3](https://github.com/jonescompneurolab/hnn-core/blob/master/hnn_core/params.py#L383). So, what @stephanie-r-jones is saying seems correct. We need to make this stuff more transparent but getting their slowly!

**Comment by rythorpe** [comment]
> > I thought the gaussian falloff was for local network connection weights but that synchronous evoked inputs targeted all relevant cells (according to their type) at the same time and same strength. Is that not correct?
> 
> The gaussian fall-off is controlled by the "lamtha" parameter. For rhythmic inputs, it seems to be [set at 100](https://github.com/jonescompneurolab/hnn-core/blob/master/hnn_core/params.py#L311) and for evoked inputs, it's [set at 3](https://github.com/jonescompneurolab/hnn-core/blob/master/hnn_core/params.py#L383). So, what @stephanie-r-jones is saying seems correct. We need to make this stuff more transparent but getting their slowly!

Sure enough. Maybe we can add `lamtha` as an optional argument in our updated feed-creation API.

**Comment by jasmainak** [comment]
@rythorpe I'm closing this issue. It seems to be resolved now that we have a new feed-creation API and lamtha is a parameter with a different name -- `space_constant`
