### ISSUE TITLE
investigate why pos_dict needs a separate key for each spike pattern

### ISSUE THREAD

**Issue by jasmainak** [jonescompneurolab/hnn-core#123]
Since all the common and unique feeds are assigned to the same location, the `pos_dict` does not need keys for each of them. See [related discussion](https://github.com/jonescompneurolab/hnn-core/pull/122#discussion_r460982632) with @rythorpe

**Comment by jasmainak** [comment]
@rythorpe is this discussion relevant any more? Can we close this issue?

**Comment by rythorpe** [comment]
> @rythorpe is this discussion relevant any more? Can we close this issue?

Nope, we've moved way past this.
