### ISSUE TITLE
network connection should not depend on spike pattern?

### ISSUE THREAD

**Issue by jasmainak** [jonescompneurolab/hnn-core#124]
@rythorpe you might be interested in this. I was looking into how a cell receives connections and realized that there are conditional statements in the network connection that depend on the input spike pattern. See here:

https://github.com/jonescompneurolab/hnn-core/blob/master/hnn_core/pyramidal.py#L534-L593 

do you have any idea why the `extpois` and `extgauss` might have different connection patterns?

**Comment by rythorpe** [comment]
I believe `extgauss` input times and synaptic weights are distributed to cells based on a spatial Gaussian distribution. `extpois` feeds probably don't have a spatial center, so their target connection pattern should be different.

**Comment by rythorpe** [comment]
@samnemo @blakecaldwell is that correct?

**Comment by jasmainak** [comment]
> so their target connection pattern should be different.

I see, interesting. Can we document what these different input types do somewhere? What are the connection and spike patterns etc? I still don't know what are the differences between them :-(

Also, if we want to separate the cortical column model from the input, this method should be part of a `ExtGauss` class rather than part of the `Pyramidal` or `Basket` class

**Comment by rythorpe** [comment]
> I see, interesting. Can we document what these different input types do somewhere? What are the connection and spike patterns etc? I still don't know what are the differences between them :-(

Yes, this definitely should be done. Somewhere in all of this is the explanation for #115.
> Also, if we want to separate the cortical column model from the input, this method should be part of a `ExtGauss` class rather than part of the `Pyramidal` or `Basket` class

Agreed, however, we might need to keep the NEURON references within the `Pyramidal` and `Basket` cell classes.

**Comment by blakecaldwell** [comment]
> > Also, if we want to separate the cortical column model from the input, this method should be part of a `ExtGauss` class rather than part of the `Pyramidal` or `Basket` class
> 
> Agreed, however, we might need to keep the NEURON references within the `Pyramidal` and `Basket` cell classes.

@rythorpe's explanation sounds right. It also makes sense that there should be a separation. Ideally feeds connected/removed from the cortical column independently. However, the need to be connected at some point. What's the argument for putting these functions in `ExtFeed`. They could certainly be made separate functions because there's no code reuse with the conditionals now.

**Comment by jasmainak** [comment]
The only argument to put them as methods of `ExtFeed` is if the connections depend on the feed type. If the connections don't depend on the feed type, I can see how you need only a single function to connect. It's a bit hazy in my mind though, we'll have to start touching the code :)

**Comment by jasmainak** [comment]
I believe this is also closed by #164 

the lines originally referred have changed but I think it has been fixed. Please feel free to reopen if you disagree
