### ISSUE TITLE
gid-to-node assignment should happen within Cell object

### ISSUE THREAD

**Issue by rythorpe** [jonescompneurolab/hnn-core#128]
Rather than having a `NeuronNetwork` instance modify a cell's gid-to-node assignment within a parallel context (i.e., via `_PC.set_gid2node(gid, rank)`, we should try delegating [the task](https://github.com/jonescompneurolab/hnn-core/blob/bcba70519303962b4eb44fe19618d7fc474bbbb1/hnn_core/neuron.py#L309-L336) to the `_Cell` and `_ArtificialCell` classes. This way, the `Network` or `NeuronNetwork` classes can simply create a list of gid values and let the cell objects handle their respective NEURON backends.

**Comment by jasmainak** [comment]
will the `_Cell` class be assigned a `rank` from `NeuronNetwork` class? how do you envision this happening? will that be a parameter of the constructor of the `_Cell` class?

**Comment by rythorpe** [comment]
> will the `_Cell` class be assigned a `rank` from `NeuronNetwork` class? how do you envision this happening? will that be a parameter of the constructor of the `_Cell` class?

@jasmainak I was thinking `_Cell` would assign `rank` in the constructor.

**Comment by jasmainak** [comment]
so you still need the loop in the `Network` class, just moving the call for `set_gid2node` inside the `_Cell` class right?

**Comment by rythorpe** [comment]
> so you still need the loop in the `Network` class, just moving the call for `set_gid2node` inside the `_Cell` class right?

Something like that. Would it be possible to just have each `_Cell` instance call `_PC.set_gid2node()` in its constructor?

**Comment by blakecaldwell** [comment]
> Something like that. Would it be possible to just have each `_Cell` instance call `_PC.set_gid2node()` in its constructor? If not, I believe there are multiple places where `Network` iterates through all the cell objects, so it might be nice to consolidate.

Perhaps. It appears that `set_gid2node` as part of the constructor would still get called in parallel, since `Cell`'s are also created in parallel:
https://github.com/jonescompneurolab/hnn-core/blob/bcba70519303962b4eb44fe19618d7fc474bbbb1/hnn_core/neuron.py#L365

I think this would work. However, the time to create the network should still be measured before and after to make sure there isn't a performance regression.

**Comment by jasmainak** [comment]
@rythorpe still relevant?
