### ISSUE TITLE
simplify process for initializing cell-to-cell connections

### ISSUE THREAD

**Issue by rythorpe** [jonescompneurolab/hnn-core#129]
Currently, various functions and wrappers are involved in allowing a `NeuronNetwork` instance to establish cell-to-cell (i.e., local network and feed) connections:

1. `NeuronNetwork()._build()` calls [`_parnet_connect()`](https://github.com/jonescompneurolab/hnn-core/blob/bcba70519303962b4eb44fe19618d7fc474bbbb1/hnn_core/neuron.py#L423-L445)

2. `NeuronNetwork()._parnet_connect()` then calls `parconnect()`, `parreceive()`, and `parconnect_ext()` within one of the child cell classes (e.g., [Pyramidal](https://github.com/jonescompneurolab/hnn-core/blob/bcba70519303962b4eb44fe19618d7fc474bbbb1/hnn_core/pyramidal.py#L407-L596)).

3. `Pyramidal().parconnect()` then calls [`Pyramidal._connect()`](https://github.com/jonescompneurolab/hnn-core/blob/bcba70519303962b4eb44fe19618d7fc474bbbb1/hnn_core/cell.py#L165-L188) and `Pyramidal().parreceive()` and `Pyramidal().parconnect_ext()` calls [`Pyramidal()._parconnect_from_src()`](https://github.com/jonescompneurolab/hnn-core/blob/bcba70519303962b4eb44fe19618d7fc474bbbb1/hnn_core/cell.py#L313-L344) (all of which are inherited from the parent `_Cell` class). (Same for the basket cell class.)

4. Finally, [`_PC.gid_connect()`](https://github.com/jonescompneurolab/hnn-core/blob/bcba70519303962b4eb44fe19618d7fc474bbbb1/hnn_core/cell.py#L334) is called from the `Pyramidal()._parconnect_from_src()` which is the lowest common python element in establishing a cell-to-cell connection.

It would be nice to rearrange and simply this process so that it is more transparent to `Network` how and when network connections are made. Ideally, there would be a single function, a method in `_Cell`, that `Network` could call in order to create a given cell-to-cell connection.

**Comment by jasmainak** [comment]
I would love to discuss this. +100

**Comment by blakecaldwell** [comment]
Agreed! The reason that it was moved out of `Network` was because it used `_PC`. However, moving to `_Cell` with a `from .neuron import _PC` inside the function sounds great.

**Comment by rythorpe** [comment]
> Agreed! The reason that it was moved out of `Network` was because it used `_PC`. However, moving to `_Cell` with a `from .neuron import _PC` inside the function sounds great.

I think it's a great policy to keep all hoc references out of `Network` - good call @blakecaldwell. We should definitely try to maintain this moving forward. Should we anticipate encountering any pickling or parallelization errors by moving this `_PC` reference to `_Cell`?

**Comment by blakecaldwell** [comment]
> Should we anticipate encountering any pickling or parallelization errors by moving this `_PC` reference to `_Cell`?

We should be fine. `_PC` is already imported in `cell.py` and existing functions heavily rely on `h.` objects.

**Comment by jasmainak** [comment]
is there still stuff to do here after #164 ?

**Comment by rythorpe** [comment]
> is there still stuff to do here after #164 ?

Nope, I think you covered it! Thanks @jasmainak!
