### ISSUE TITLE
discrepancy between simulation trial variability in HNN vs hnn-core

### ISSUE THREAD

**Issue by rythorpe** [jonescompneurolab/hnn-core#136]
I'm experiencing an issue where I get significantly different results, particularly noticeable in the inter-trial variability, in HNN versus hnn-core. Running the attached param file in HNN (top) and hnn-core (bottom) using the attached python script, I get the figures shown below. Furthermore, I haven't been able to reproduce this issue using the default parameter set.

![Screenshot from 2020-08-11 15-05-02](https://user-images.githubusercontent.com/20212206/89941514-20a88780-dbe9-11ea-877e-dd2de3ddbcfa.png)
![Screenshot from 2020-08-11 15-20-03](https://user-images.githubusercontent.com/20212206/89941507-1e462d80-dbe9-11ea-86eb-3e3e4794ad7c.png)

[issue_demo.zip](https://github.com/jonescompneurolab/hnn-core/files/5059115/issue_demo.zip)

**Comment by rythorpe** [comment]
Also note that the input histograms are drastically different.

**Comment by jasmainak** [comment]
sorry I didn't look at the zip file. Might be better to share via gist, so I can copy paste. You can have the param file as a dictionary in the Python script to avoid loading it.

could it be that `sync_evinput` is ignored somewhere? The input histograms being different is certainly weird.

**Comment by rythorpe** [comment]
@jasmainak try [this](https://gist.github.com/rythorpe/e7bac070bff41f108996b98c8b58ac14).

> could it be that `sync_evinput` is ignored somewhere? The input histograms being different is certainly weird.

Possibly, though I don't understand why some trials would still have a small amount of jitter s.t. entire clumps of trials are still exactly the same. Note that `sync_evinput = True` for this parameter set, however, the problem persist when `sync_evinput = False`.

**Comment by rythorpe** [comment]
I also tried running the same simulation with 25 trials using the `JoblibBackend` and got the following image. Isn't the `JoblibBackend` supposed to provide jitter across trials?

![Screenshot from 2020-08-12 15-41-01](https://user-images.githubusercontent.com/20212206/90061019-8cefbd80-dcb3-11ea-8d57-895e5213d97e.png)

**Comment by jasmainak** [comment]
it could be that using seeds to jitter the trial may not be working in this case for whatever reason. Will need to investigate. Should we set up another pair programming session @rythorpe ?

By the way, I do think we should move away from "let's compare to HNN as ground truth" philosophy at some point. Because HNN does not have any unit tests either, so there isn't really a strong notion of correctness in that sense. What we have in HNN is outputs which make sense for some scenarios. 

I have seen software where 2 bugs cancel each other and the output makes sense for some inputs but not for others. We need a stronger definition of what's a bug, otherwise it will hamper development of the software.

**Comment by rythorpe** [comment]
> it could be that using seeds to jitter the trial may not be working in this case for whatever reason. Will need to investigate. Should we set up another pair programming session @rythorpe ?

@jasmainak sure, let's give it a shot!

> By the way, I do think we should move away from "let's compare to HNN as ground truth" philosophy at some point. Because HNN does not have any unit tests either, so there isn't really a strong notion of correctness in that sense. What we have in HNN is outputs which make sense for some scenarios.
>
> I have seen software where 2 bugs cancel each other and the output makes sense for some inputs but not for others. We need a stronger definition of what's a bug, otherwise it will hamper development of the software.

We can discuss this more in-person, but as a contributor, I completely agree that HNN shouldn't be used as ground truth. As a user with a previously-created, HNN-generated param file, I just want to identify what is wrong with my param file so that I can run similar (i.e., not necessarily identical) simulations in hnn-core.

I think this issue represents a case where a (potential) bug has emerged that prevents hnn-core from accomplishing a basic use-case that HNN currently implements correctly (i.e. providing uniform stochasticity across simulation trials). Most likely, the discrepancy outlined in this issue is not a bug in hnn-core but rather a difference in how HNN and hnn-core reference some elusive parameter. However, if a bug does indeed exist that has eluded us despite hnn-core's tests, the functionality of HNN can provide us with a useful sanity check.

**Comment by blakecaldwell** [comment]
> By the way, I do think we should move away from "let's compare to HNN as ground truth" philosophy at some point. Because HNN does not have any unit tests either, so there isn't really a strong notion of correctness in that sense. What we have in HNN is outputs which make sense for some scenarios.

At some point, `hnn-core` will be considered "ground truth". More accurately, the "current state of the model", It is important to systematically understand where differences are coming from, whether a bug in new code or a fix in new code. Both have been found in developing `hnn-core`.

**Comment by blakecaldwell** [comment]
@rythorpe `hnn-core` `master` in my experience has never provided variable results for different trials, no matter tha backend. There is a bug in `hnn-core`. I forgot exactl where, maybe the seeds for different trials.

If we can reproduce HNN seeding in the first pull request, these checks can be run. We can then have another issue/PR for more logical seeding of random variables in each trial.

**Comment by jasmainak** [comment]
> @rythorpe hnn-core master in my experience has never provided variable results for different trials, no matter the backend. There is a bug in hnn-core. I forgot exactly where, maybe the seeds for different trials.

@blakecaldwell but try this:

```sh
$ git checkout 015124c36ba0632391a2532a1166c201e1153841
$ python examples/plot_simulate_evoked.py
```

it did have randomness before ...

**Comment by blakecaldwell** [comment]
@jasmainak, indeed, but there is still a problem with the seeds where more than one trial use the same seed (and have identical results). Described in more detail in #113
