### ISSUE TITLE
add functionality for running batch simulations

### ISSUE THREAD

**Issue by blakecaldwell** [jonescompneurolab/hnn-core#140]
Enable users to run a non-interactive batch of simulations of the HNN model by specifying a set of parameters values to use. This could be used for sweeping a range of parameter values (e.g. optimization), a list of specific parameter files to iterate over, and/or a distribution to draw from in choosing parameter values (e.g. priors for SNPE).

This will be a new interface for running simulations via `hnn_core.simulator` with the parameters to use specified as input and the results retrievable by their respective Python objects, and optionally saving the results/parameter files to disk.

Investigate what can be learned from how it is done in `scipy` and [NetPyNE batch simulations](http://www.netpyne.org/tutorial.html#tutorial-8-running-batch-simulations).

**Comment by jasmainak** [comment]
Also look into `scikit-learn` API: https://scikit-learn.org/stable/modules/grid_search.html#exhaustive-grid-search. I think it's neat to be able to specificy parameter names with ranges as a dictionary. It mimics closely what you would do in the GUI.

**Comment by jasmainak** [comment]
moving this to 0.3 @ntolley so we get some more time to mull over API etc.

**Comment by jchen6727** [comment]
https://github.com/jchen6727/pubtk

![batch](https://github.com/jonescompneurolab/hnn-core/assets/25700973/3a632eb2-198d-48bb-89b3-e8c4dada2626)

The goal was to create a subpackage that can easily be adapted to run on a variety of compute environments and to decrease the filesize costs of aggregating simulation results. Custom shell scripts can adapt it to any job submission syntax / how configurations are passed. This works with NetPyNE but I am not as familiar with HNN.

**Comment by jchen6727** [comment]
@ntolley 

Hello,

I'm not sure if you have drummed up any interest in your GSoC project for batch so far; however, we do have a very similar [project idea 8.2](https://neurostars.org/t/gsoc-2024-project-idea-8-2-improving-ml-ai-parameter-tuning-optimization-of-electrophysiological-models-175-350-h/28260) --especially using this batch refactor-- and have a couple of applicants now...
I think it might be interesting to fold the project ideas and tackle this as a combined project with two applicants. That way we could have two applicants working on a very similar project.

**Comment by ntolley** [comment]
Definitely would be happy to discuss! Can you send me an email at `nicholas_tolley@ brown.edu` to schedule a time to chat?
