### ISSUE TITLE
change name of variable "type"

### ISSUE THREAD

**Issue by jasmainak** [jonescompneurolab/hnn-core#151]
The variable "type" is a reserved keyword in Python and should not be used elsewhere. Changing the name of this variable to "feed_type" or whatever is appropriate everywhere in the code is a good starting issue for a new contributor

**Comment by Kartik-Khandelwal** [comment]
I will do that sir, kindly assign it to me.

**Comment by jasmainak** [comment]
go for it.

**Comment by jasmainak** [comment]
I believe this is no longer an issue since #164
