### ISSUE TITLE
define schema for output files (saving)

### ISSUE THREAD

**Issue by blakecaldwell** [jonescompneurolab/hnn-core#159]
Several classes (`Spikes`, `Dipole`, `Param`) have a `.write()` member that writes a `.txt` file based off the old HNN GUI format. It may be useful to preserve backward compatibility, but we also need a way to add new functionality. The first example of this is a `nave` attribute in the `Dipole` object as discussed in #156.

- [ ] Document the format for output files in a new `.rst` file
- [ ] Update existing `.write()` functions to save extra metadata including schema version

**Comment by jasmainak** [comment]
I would put the documentation in the docstring of the `write` file itself unless it begins to get too unwieldy? we can also have a separate `.rst` file describing the details

regarding backwards compatibility, my position is that we're still in the experimentation phase so it's important to keep things fluid. Maybe offering people tiny functions to convert from the old format to the new formats is the way to go.

**Comment by blakecaldwell** [comment]
Write methods work with HNN, or the write function is implemented in HNN. No use case for this anymore.
