### ISSUE TITLE
set up a CI for Windows

### ISSUE THREAD

**Issue by jasmainak** [jonescompneurolab/hnn-core#167]
For our Windows friends :)

**Comment by jasmainak** [comment]
@ntolley @kohl-carmen I think you guys could team up for this? There are three options that I know of:

- [appveyor](https://www.appveyor.com/)
- github workflows like we do in [mne-bids here](https://github.com/mne-tools/mne-bids/blob/master/.github/workflows/unit_tests.yml)
- microsoft azure pipelines like we do in [mne-python](https://github.com/mne-tools/mne-python/blob/master/azure-pipelines.yml)

appveyor is what we historically used in MNE and the one with which I have some experience. But it is kind of slow, so folks have moved away from it. It would be a great opportunity to learn about how continuous integration is set up. And we could catch Windows-specific problems as soon as it happens.

**Comment by ntolley** [comment]
Certainly willing to work on this but it may be 1-2 weeks before I can focus on this PR. Looks like there is a decent amount to discuss with the MPI/Windows incompatibility.

**Comment by jasmainak** [comment]
sounds good!

**Comment by jasmainak** [comment]
cc @rythorpe @ntolley if you plan on revamping the windows install, we should set up a CI. Otherwise, it will be hard to maintain.

**Comment by rythorpe** [comment]
I'd prefer not to :-). But maybe we should. Especially since adding the new GUI will probably break stuff that allows Windows to render graphics via WSL.

How are we planning on getting NEURON installed in CI?

**Comment by jasmainak** [comment]
maybe we should try to see if graphics can be rendered with WSL? I suspect a majority of GUI users will also be Windows users ... arghhhh

we could of course use WSL to install Neuron but then that's probably redundant with a linux build? The native build will be painful but maybe we could copy the CI set up from Neuron folks if we really want to do this ...

**Comment by jasmainak** [comment]
here: https://github.com/neuronsimulator/nrn/blob/master/.github/workflows/windows.yml 

we have a starting point :-) Once neuron is installed, hopefully the rest of the installation and tests go smoothly

**Comment by ntolley** [comment]
Closed by #560
