### ISSUE TITLE
Replace h.setpointer() with more intuitiveseg._ref_somevar_suffix = ptr

### ISSUE THREAD

**Issue by salvadord** [jonescompneurolab/hnn-core#175]
Robert McDougal:
"ever since 7.7, you can directly set pointers using e.g.
seg._ref_somevar_suffix = ptr
(instead of using h.setpointer which is somewhat nonintuitive)"

**Comment by jasmainak** [comment]
Thanks! Someone with more influence on Neuron development should tell them that such things need to be documented rather than being secret knowledge, e.g., in the form of release notes :)

@salvaord do you want to make the pull request? I'm also happy to do it if you don't have time
