### ISSUE TITLE
read_spikes doesn't handle an empty file properly

### ISSUE THREAD

**Issue by blakecaldwell** [jonescompneurolab/hnn-core#178]
If you have a parameter file that fails to induce spiking in cells and doesn't have any evoked inputs (e.g. only rhythmic inputs), then the `spk_0.txt` file will be empty. This causes an error in `read_spikes` (last line below). It's not clear how to skip one empty spike file because the method uses concatenation in order of trial index 0, 1, 2, 3, etc.

```
/Users/blake/repos/hnn-core/hnn_core/network.py:40: UserWarning: loadtxt: Empty input file: "/Users/blake/hnn_out/data/gamma_L5weak_L2weak_bursty/spk.txt"
  spike_trial = np.loadtxt(file, dtype=str)
(0,)
Traceback (most recent call last):
  File "/Users/blake/repos/hnn/hnn_qt5.py", line 596, in run
    self.runsim() # run simulation
  File "/Users/blake/repos/hnn/hnn_qt5.py", line 678, in runsim
    updatedat(self.params)
  File "/Users/blake/repos/hnn/simdat.py", line 121, in updatedat
    spikes = read_spikes(dfile['spk'])
  File "/Users/blake/repos/hnn-core/hnn_core/network.py", line 42, in read_spikes
    spike_times += [list(spike_trial[:, 0].astype(float))]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```

**Comment by jasmainak** [comment]
I suppose you would append an empty list to `spike_times`?

@samikane do you want to give this a shot? It looks like a nice issue to get your hands dirty with some of the code while not being too complicated.

**Comment by blakecaldwell** [comment]
@rythorpe @samikane this should be a quick fix. any takers?
