### ISSUE TITLE
access raw dipole for each trial

### ISSUE THREAD

**Issue by blakecaldwell** [jonescompneurolab/hnn-core#183]
The raw dipole before smoothing should be accessible for inspection and saving.

Perhaps `simulate` should return a rawdpl instead of the smoothed and scaled version.

https://github.com/jonescompneurolab/hnn-core/blob/073ef6c6a184677d4349e5812f1ed845857f6f74/hnn_core/dipole.py#L48

Then these lines can be moved to `simulate_dipole` after `_gather_trial_data`:
https://github.com/jonescompneurolab/hnn-core/blob/073ef6c6a184677d4349e5812f1ed845857f6f74/hnn_core/network_builder.py#L120-L123

Saving is probably best done with a parameter to `simulate_dipole` that will call `dpl.write()` before the lines above.

The parameter `save_dpl` can then be removed (used here):
https://github.com/jonescompneurolab/hnn-core/blob/073ef6c6a184677d4349e5812f1ed845857f6f74/hnn_core/network_builder.py#L117-L118

**Comment by jasmainak** [comment]
this is very similar to what we were discussing with @kohl-carmen and @klankinen during the hackathon for #149 .
