### ISSUE TITLE
hnn-core release 0.1

### ISSUE THREAD

**Issue by jasmainak** [jonescompneurolab/hnn-core#193]
Hey all, 

We should set a timeline for hnn-core release. I have a bit more time in the coming days, so can push this. I suggest the following:

- integration of hnn-core into HNN by Nov 1
- test dev version of HNN with dev version of hnn-core with students/lab members
- release of hnn-core by Dec 1. Make it clear that this is still an alpha/beta release and API in next cycle may break old code. The release is mainly for HNN to be able to use hnn-core
- test dev version of HNN with release version of hnn-core with students/lab members
- release HNN by Dec 15 or Christmas
- tweet

cc @blakecaldwell @cjayb @stephanie-r-jones @rythorpe @ntolley and anyone else who is interested :)

**Comment by jasmainak** [comment]
Update: I have changed the deadline for the release and labeled certain issues for [milestone 0.1](https://github.com/jonescompneurolab/hnn-core/milestone/1). Please feel free to comment on individual issues/pull requests if you feel they should be added or removed. I think we are getting close to an alpha release.

For the release to Pypi, if someone wants to learn (@ntolley @rythorpe ?), happy to do it over zoom. Might take a couple of hours though. And we should add notes in the wiki how to do it.

**Comment by rythorpe** [comment]
> For the release to Pypi, if someone wants to learn (@ntolley @rythorpe ?), happy to do it over zoom. Might take a couple of hours though. And we should add notes in the wiki how to do it.

@jasmainak if you haven't done this already, I'd be interested in learning how to do this.

**Comment by jasmainak** [comment]
not done yet :) we need to close milestone 0.1 first though ... either merge the PRs or move the issues to next milestone

**Comment by jasmainak** [comment]
closed by #255
