### ISSUE TITLE
scaling of cell positions

### ISSUE THREAD

**Issue by jasmainak** [jonescompneurolab/hnn-core#202]
I [discovered](https://github.com/jonescompneurolab/hnn-core/pull/200#discussion_r518937845) in #200 that the cell positions are scaled in a somewhat odd way:

https://github.com/jonescompneurolab/hnn-core/blob/bb559b7879c2bf9823d42717438a52b22378e75c/hnn_core/cell.py#L154

This seems like a bug to me but maybe we are missing something. Two questions:

- why is `self.pos[2]` passed instead of `self.pos[1]` for y coordinate
- why is `self.pos[2]` not scaled by 100?

It's not super-clear where this factor 100 comes from. Since the dipole moment = current * distance, this will affect the final result. cc @stephanie-r-jones @rythorpe

**Comment by rythorpe** [comment]
@jasmainak I just realized that in nrn-space, the apical dendrite [extends along the y-axis](https://github.com/jonescompneurolab/hnn-core/blob/eb173119b1832be6b170c25e738b978e74f05d73/hnn_core/pyramidal.py#L469) and contributes to the [net dipole](https://github.com/jonescompneurolab/hnn-core/blob/eb173119b1832be6b170c25e738b978e74f05d73/hnn_core/cell.py#L180) along with all other dendrites with a y-components. Note that the soma and apical dendrite are modeled as cylinders who's aligned axes extends along the 2nd dimension.

**Comment by jasmainak** [comment]
not sure I follow. `yscale` (ideally should be cos theta) is [hard coded](https://github.com/jonescompneurolab/hnn-core/blob/eb173119b1832be6b170c25e738b978e74f05d73/hnn_core/pyramidal.py#L501) and the scale is applied [here](https://github.com/jonescompneurolab/hnn-core/blob/eb173119b1832be6b170c25e738b978e74f05d73/hnn_core/cell.py#L213). The actual orientation (angle) of the dendrite is not used anywhere ...

**Comment by rythorpe** [comment]
> not sure I follow. `yscale` (ideally should be cos theta) is [hard coded](https://github.com/jonescompneurolab/hnn-core/blob/eb173119b1832be6b170c25e738b978e74f05d73/hnn_core/pyramidal.py#L501) and the scale is applied [here](https://github.com/jonescompneurolab/hnn-core/blob/eb173119b1832be6b170c25e738b978e74f05d73/hnn_core/cell.py#L213). The actual orientation (angle) of the dendrite is not used anywhere ...

The points that define the extent of the cylindrical soma and apical dendrites create an axis along the 2nd dimension. Unless these compartments get rotated somewhere in the code that I'm unaware of, this convention is maintained by translating the 2nd (y) dimension of the nrn model by `self.pos[2]` (what we visualize as the z-dimension in the high-level python model).

I think you're right that it doesn't explicitly calculate the y-component, however, across the population, the net contribution of other components should be negligible. (I don't completely understand what is going on `h.Dipole`.)

**Comment by cjayb** [comment]
My head's spinning with the orientations here. Can we agree on what the three cardinal axes are? It seems like `y` is used as the axis parallel to the apical dendrite orientation. Do you agree?

**Comment by rythorpe** [comment]
> My head's spinning with the orientations here. Can we agree on what the three cardinal axes are? It seems like `y` is used as the axis parallel to the apical dendrite orientation. Do you agree?

Correct, that is my understanding. Personally, I think we should change this in the model so that 'z' || apical dendrite orientation.

**Comment by cjayb** [comment]
I think so too, though I'd like to understand the original reason for choosing the axis order. Is there a NEURON convention this is following? Or is it simply that HNN was conceived as a 2D (xz-)model, so it made sense to align the dipole moment with the second?

@samnemo perhaps you can shed light here too?

**Comment by jasmainak** [comment]
see here: https://github.com/jonescompneurolab/hnn-core/blob/00ebb0fff014c32d0a6b151c45a5ed36cce7c284/hnn_core/basket.py#L30-L32

this may answer some questions
