### ISSUE TITLE
Documenting HNN parameters

### ISSUE THREAD

**Issue by blakecaldwell** [jonescompneurolab/hnn-core#214]
I was about to reimplement HNN's "tooltip" functionality in https://github.com/jonescompneurolab/hnn/pull/232, but it involves documenting what each parameter does. Since managing the parameter space is within hnn-core's arena, I thought we could come up with a plan here to solve the issue for both projects. Would love some input @jasmainak on how to store these definitions in a way that can generate html docs that both projects can point at.

The background on tooltips is that it was originally implemented as a global dictionary with keys matching parameter names and then a string with user-readable text explaining the function. The dictionary was built from the `[tips]` section of this file
https://github.com/jonescompneurolab/hnn/blob/master/hnn.cfg#L20 (note that it's incomplete)

So building off of a standard way of documenting configuration files ( @jasmainak ), can we come up with a more thoughtful way of storing mappings between parameter names and useful one-line descriptions? Perhaps the generated html can include detailed descriptions, but the short descriptions are useful in the GUI when the user hovers over the specific parameter field.

**Comment by jasmainak** [comment]
umm ... do you want to reuse this in code as well?

I think plain `rst` files are a good idea like we discussed elsewhere. Maybe we could use the [glossary](https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#glossary) directive. But no strong feelings

**Comment by ntolley** [comment]
We've followed thorough documentation for almost all parameters so this can be closed
