### ISSUE TITLE
Support plotting rhythmic feed histograms from saved spike files

### ISSUE THREAD

**Issue by blakecaldwell** [jonescompneurolab/hnn-core#219]
If a simulation is run, then the CellResponse objects are saved to file via their `write()` method, it is not currently possible to completely recover which gids belong to rhythmic feeds as they are all labeled with `common` in `spike_types`.

HNN needs this capability to load a saved spike file and plot the histograms for rhythmic feeds without having to run the simulation again. Note, this is not an issue with evoked inputs

Probably the easiest way to accomplish this would be to expand the labels used in `spike_types` to be in 1:1 correspondence with the type of feed.

Alternatively CellResponse could be written to a new file as a whole object, including `gid_ranges`. A load member would be necessary too. This is how legacy HNN does it, but its naming and reuse of `param.txt` is not ideal.

**Comment by rythorpe** [comment]
It seems to me that there are two separate issues here: 1) we have limited transparency in how rhythmic feeds are labeled and stored and 2) there is a lack of functionality for plotting rhythmic feeds. I know @cjayb has been working on refactoring how feeds are created and stored, and his proposed plan will solve (1). However, an entirely new API for creating feeds may complicate the hnn-gui/-core merge process.

On the other hand, if we are just looking for a quick and easy way to reproduce the plotting behavior of the current gui, we should be able to leverage the fact that the first `common` gid always corresponds to a proximal rhythmic feed and the second `common` gid always corresponds to a distal rhythmic feed.

**Comment by blakecaldwell** [comment]
Right now, I'm doing all of the rhythmic feed plotting in HNN, so issue number 2 can be dealt with later. I realize the title is a little misleading.

Also, this isn't blocking the HNN integration, because I just save the `gid_ranges` in param.txt similar to how it was done before. It'd just be nice to stop doing it that way. I'd say to queue this up as part of the larger effort to do things the right way.

**Comment by jasmainak** [comment]
Can we add it to tomorrow's meeting agenda? I'm a bit lost ... sounds like having a 1:1 correspondence is the best way? 

Is this critical for 0.1 release?

**Comment by blakecaldwell** [comment]
Not critical. Just there's a lot of reading and writing files (basically the way HNN has always been).

**Comment by jasmainak** [comment]
Let's discuss this sometime @rythorpe . Looks like a good item for 0.2

**Comment by rythorpe** [comment]
Maybe we can add this to Monday's discussion @jasmainak?

**Comment by jasmainak** [comment]
Sure!
