### ISSUE TITLE
Nomenclature: 'feeds', 'drives' and 'biases'

### ISSUE THREAD

**Issue by cjayb** [jonescompneurolab/hnn-core#222]
### Driver
* Standard neuroscience parlance refers to things like feedforward and feedback _drive_ that is valid for both single cells and groups of them.
* Neymotin et al. (2020) refers to “Exogenous driving inputs” (pp. 29–31)
  * “Evoked” driver: “trains of synaptic inputs to the local network during a sensory stimulus”
  * “Rhythmic” driver: “typically bursts of action potentials that drive the local network rhythmically”
* Proximal (a.k.a. “granular”, i.e., via L4) or distal (See Fig 7A)
  * Both have strong semantic connotations in HNN: not a general-purpose simulation tool, but rather one that incorporates (imposes) physiological constraints
  * Related to target dispersion of  FF vs. FB (or associative thalamic) pathways (drives)

### Bias ?
Neymotin et al. (2020)
* _“Tonic inputs are modeled as somatic current clamps with a fixed current amplitude (nA)”_ 
  * __for each modeled neuron type separately__
* _“Noisy Inputs are trains of action potentials that follow a Poisson Process and create excitatory AMPA or NMDA synaptic inputs to the somata of __all neurons of a given type__.”_

### Feed ?
* was this used as an umbrella for both the above?

**Comment by cjayb** [comment]
Moved this discussion here from #221 
Ping @jasmainak @rythorpe @ntolley others?

**Comment by cjayb** [comment]
As far as I can tell, the reference paper does not mention feeds, so I don't think the API should either; wdyt? Note also how tonic and poisson inputs are grouped as 'biases', as opposed to evoked or rhythmic 'drivers'. I feel this is a bigger decision than the 'docs'-label, @jasmainak : should #221  implement 'drives' or 'feeds'?

**Comment by rythorpe** [comment]
> As far as I can tell, the reference paper does not mention feeds, so I don't think the API should either; wdyt? Note also how tonic and poisson inputs are grouped as 'biases', as opposed to evoked or rhythmic 'drivers'. I feel this is a bigger decision than the 'docs'-label, @jasmainak : should #221 implement 'drives' or 'feeds'?

I think we should maintain the vocabulary used in Neymotin et al. and separate the API accordingly. "Drive" can be used to connote an evoked or rhythmic input that emerges via a feed-forward or feedback pathways. "Bias" can be used to connote some kind of baseline feed that emerges from within the network (e.g., poisson or tonic input) that is designed to bring the network to some kind of steady-state mode (even if it does so only transiently).

**Comment by cjayb** [comment]
I also think being consistent with the paper, as well as other papers in the field, makes sense---'feeds' don't have a biological connotation.

I personally like the word 'drive', but another one used in the paper is (exogenous) __'input'__. So we'd have
1. evoked input/drive
1. rhythmic input/drive
1. noisy input/drive (e.g. Poisson)
1. tonic input/bias (current clamp)
where the last one has a very different implementation compared with the others.

A 'drive' makes sense physiologically for 1-3. 4 is more of a 'bias', though one that's implemented as an 'input' directly to the cell soma (never synapses).

I'll try some ideas out in #221

**Comment by jasmainak** [comment]
That's fine calling it a "drive". I'm wondering if #221 is the right PR for that though. Because if you try to make it consistent and call it `drive` everywhere, you end up with a large diff. Let's try to focus on getting it to work in #221. In a follow up PR, we can rename it to "drive" everywhere.

For 3. and 4., do you imagine a separate function or the same function as for 1. and 2.? One complication is that evoked inputs can also be cell-specific, right?

**Comment by cjayb** [comment]
Whoops, didn't see this until after my latest push... It's a large diff, yes, but it's kinda integral to the whole cleanup process so I included it. Need to merge this PR before I can get CI results though... Tests are passing locally of course. 

> For 3. and 4., do you imagine a separate function or the same function as for 1. and 2.? One complication is that evoked inputs can also be cell-specific, right?

In the latest push, 1-3 are all 'drives', and 4 is a 'bias'. It actually cleaned up `Network` quite nicely, see what you think.
And yes: 1-3 can all be 'cell-specific' or 'common', as far as I can tell. In the 'classic' implementation, 1, 3 and 4 are cell-specific, 2 are 'common'.
