### ISSUE TITLE
plot_spikes_raster does not plot spiking pattern of individual cells

### ISSUE THREAD

**Issue by jasmainak** [jonescompneurolab/hnn-core#227]
In [plot_spikes_raster function](https://github.com/jonescompneurolab/hnn-core/blob/bc8e4f24a97413cdf168e2d1ee35e38197671254/hnn_core/viz.py#L149), aggregate of spiking pattern over all cells in a cell type is shown. I think we should plot each cell individually. That way, we can see patterns like synchronous spiking etc (e.g., gamma tutorial on HNN website). We want something like this:

![](https://raw.githubusercontent.com/jonescompneurolab/hnn-tutorials/master/gamma/images/image12.png)

easy issue for you to tackle when bored @ntolley ?

**Comment by ntolley** [comment]
Sure shouldn't be too bad. I actually already have some code written to do this from an old figure. I'll open a PR soon.

**Comment by jasmainak** [comment]
Perfect, looking forward!!
