### ISSUE TITLE
better handling of tstop

### ISSUE THREAD

**Issue by jasmainak** [jonescompneurolab/hnn-core#230]
We [discovered](https://github.com/jonescompneurolab/hnn-core/pull/228#issuecomment-749487197) that `tstop` needs to be handled better. In particular,

1. event_times beyond tstop should be truncated
2. tstop should be passed passed explicitly to simulate_dipole

@kohl-carmen this might be a good issue for you. 2. is pretty similar to what you did with `postproc`. 1. might need some thinking but is doable I think.

**Comment by cjayb** [comment]
Hopefully the solution will also make the `tstop`-variable unnecessary here:

https://github.com/jonescompneurolab/hnn-core/blob/31b2a93faafcf693004e9c7742cafe4f54bb1f57/hnn_core/network.py#L350-L355

**Comment by jasmainak** [comment]
slightly more difficult issue @alexrockhill

**Comment by jasmainak** [comment]
This is closed by #397 . Turned out to be not a "good first issue". I removed the label :)
