### ISSUE TITLE
bursty drive with 'uniform' distribution: need and implementation?

### ISSUE THREAD

**Issue by cjayb** [jonescompneurolab/hnn-core#232]
Neymotin et al. (2020) make no mention (pp. 30-31) of 'bursty' inputs with a _uniform_ distribution of input events. It seems that the only allowed distribution is _gaussian_, with

> Burst stdev (ms) - standard deviation of input events

1. Is the 'uniform' option used for anything? @stephanie-r-jones @blakecaldwell @rythorpe @ntolley 
2. Looking at `_create_common_input` (currently in feeds.py), it seems that the implementation of `uniform` is a bit _ad hoc_; we need to either fix it or remove it.

Discussed in #221

**Comment by jasmainak** [comment]
> Is the gaussian ('normal') option

you mean "uniform" ?

**Comment by cjayb** [comment]
> you mean "uniform" ?

I do!

**Comment by rythorpe** [comment]
I'm a little confused by the intention behind the original code in `_create_common_input()`: 

```python
  if distribution == 'normal':
      # array of mean stimulus times, starts at t0
      isi_array = np.arange(t0, tstop, 1000. / f_input)
      # array of single stimulus times -- no doublets
      t_array = prng.normal(np.repeat(isi_array, repeats), stdev)
  elif distribution == 'uniform':
      n_inputs = repeats * f_input * (tstop - t0) / 1000.
      t_array = prng.uniform(t0, tstop, n_inputs)
```

If I understand correctly, for normally distributed common inputs, we'll get an array of input spikes like

```
___||___||___||___
__||___||___||____
____||___||___||__
```
(i.e., where the time of each burst in a given repeat is selected from a normal distribution centered at a regular interval) for `repeats=3` and `events_per_cycle=2`. Conversely, uniformly distributed common inputs, we'll get

```
__||_____||_||____
_||___||______||__
_____||__||____||_
```
(i.e., where the time of each burst in a given repeat is selected from a uniform distribution and *not* at a regular interval).

**Comment by rythorpe** [comment]
I'm guessing that the periodic normally distributed bursty drive simulates a rhythmic process whereas the uniformly distributed bursty drive simulates a non-rhythmic process?

**Comment by jasmainak** [comment]
I vote for removing this. If a need crops up in the future, it's easy to add back by going back at the git commit and copying the code.

**Comment by cjayb** [comment]
+1 for removing
