### ISSUE TITLE
Refactor `feed` into `drives` using new API calls, and improve transparency of `_instantiate_drives`

### ISSUE THREAD

**Issue by cjayb** [jonescompneurolab/hnn-core#233]
The API-update in #221 renamed exogenous inputs 'drives' and added new `add_`-methods to `Network`. The new `drives` module currently only does input checking, but should be updated:

1.  The `feed`-module contains legacy code that should be deprecated. In particular, the use of a wrapper function to generate (random) event times should be axed in favour of `Network._instantiate_drives` calling the relevant generator-functions explicitly (based on drive type).
2. The entire `test_feed.py` should be deprecated, and replaced by an updated `test_drives.py`, which uses the new API calls to test generation of event times for the various drives.

**Comment by jasmainak** [comment]
Could 1. potentially allow users to plot the input spikes before the simulation? I think that might be good to have before 0.1 release if possible but I can also move this to 0.2 if you like

**Comment by cjayb** [comment]
I'm closing this because the code has already moved on. Further improvements of the drives will follow from #234 and #244
