### ISSUE TITLE
need for cloning Network's and modifying drives?

### ISSUE THREAD

**Issue by cjayb** [jonescompneurolab/hnn-core#235]
We added `add_`-methods to add drives to `Network` in #221 (EDIT: and a `copy`-method too). To allow rapid (and "clean") iterations over several variations in drive parameters, it may be useful to have the possibility of _copying_ and then _modifying_ existing `net`'s, such as

```python
net = Network(params)
net.add_XXX_drive( ... )
...
clone_net = net.copy()
clone_net.modify_drive(name, dynamics=new_dynamics)
...
```

For example, `plot_simulate_evoked.py` could simply do:

```python
net = Network(params, initialise_hnn_drives=False)
net.add_evoked_drive('evdist1', ...)
net.add_evoked_drive('evprox1', ...)
net.add_evoked_drive('evprox2', ...)
...
net_sync = net.copy()
# set `sigma=0` for `sync_evinput`
net_sync.modify_drive('evdist1', dynamics={'sigma': 0})
net_sync.modify_drive('evprox', dynamics={'sigma': 0})
net_sync.modify_drive('evprox2', dynamics={'sigma': 0})
...
```

**Comment by jasmainak** [comment]
In your current API proposal, couldn't we simply do:

```py
net.external_drives['evdist1']['dynamics']['sigma'] = 0
simulate_dipole(net)
```

? Just thinking of alternative proposals/ideas. Of course this ties in with our discussion of "delayed" instantiation

**Comment by cjayb** [comment]
This is dangerous. Currently `_instantiate_drives` is only called if you explicitly pass `n_trials` to `simulate_dipole`. We could change it to be called _always_, but that would make event times unpredictable.

If we support modifying parameters, I think we should wrap them in a method that does things like re-initialising the `prng` etc.

**Comment by blakecaldwell** [comment]
I like this feature for reducing how many times `Network` objects get sent to MPI processes during optimization. A way of sending `modify_drive` parameters to the child processes (via `stdin`) would be needed as well.

**Comment by jasmainak** [comment]
@cjayb is this issue still relevant? We have a `net.copy`. As for modifying drives, do you still consider modifying the `net.external_drives` directly to be dangerous as I suggested [here](https://github.com/jonescompneurolab/hnn-core/issues/235#issuecomment-751895587)? After #397 `_instantiate_drives` is called only in `simulate_dipole`.

One argument to have a dedicated method might be to allow easy changes to the internal data structure. Then you will make `net._external_drives` private and modify only through the method. Seems a bit of an overkill for now?

**Comment by cjayb** [comment]
I think the API has moved on, so closing this now as obsolete.
