### ISSUE TITLE
implementation of synaptic delays & decays

### ISSUE THREAD

**Issue by cjayb** [jonescompneurolab/hnn-core#238]
From Neymotin et al. (2020), pp. 29-30:

> There is all-to-all connectivity between any two populations of synaptically-coupled neurons. Synaptic weights between the neurons are scaled inversely by the distance in the XY plane (arbitrary units) between the neurons (d) using exponential fall-off following <img src="https://render.githubusercontent.com/render/math?math=%24e%5E%7B-d%5E2%2F%5Clambda%5E2%7D%24">, and space constant lambda, which depends on pre- and post-synaptic type.

> The synaptic delays are scaled in proportion to the XY plane distance (d) between the neurons following <img src="https://render.githubusercontent.com/render/math?math=%241%20%2F%20e%5E%7B-d%5E2%2F%5Clambda%5E2%7D%24">, to account for the larger propagation distance (note that the lambda value is determined using values in Table 2). With increasing _d_ between neurons, the synaptic weights decay, while the synaptic delays increase.

The drive methods added in #221 include parameters

```python
space_constant=3.  # a.k.a lambda
dispersion_time=0.1  # synaptic delay at d=0
```

It is currently not clear what is happening. Legacy code used the variable name `lamtha` to refer to both spatial and pseudo-temporal decay. The term `dispersion_time` introduced in #221 is also a misnomer. __We need a more descriptive name for the parameters, and possibly are revamp of user-facing parameter choices.__

One proposal (#221) is to bundle the two into a dict:

```python
synaptic_delay=dict(amplitude, space_constant)
```

Note that all artificial drive cells are placed in the `origin` of the network, meaning that weights decrease and delays increase towards the edges of the network. Have the effects of this (on the dipole moment) been analysed anywhere?

**Comment by jasmainak** [comment]
since `space_constant` is used in both delays and weights, I think I've changed my mind about bundling them into one parameter. Perhaps `dispersion_time` could be called `max_synaptic_delay` ?

**Comment by cjayb** [comment]
more like `min_synaptic_delay`... but does it capture all we need it to? Clearly this isn't something a user should fiddle with! But if it's exposed, it should make sense.

**Comment by cjayb** [comment]
> Should we just rename dispersion_time (weird) to synaptic_delays, as I proposed originally? Then let space_constant do its thing on both (and add mention of it to docs).

**Comment by jasmainak** [comment]
yeah let's do that and we can close this issue I suppose
