### ISSUE TITLE
HNN GUI Beta Event Tutorial Discrepancy

### ISSUE THREAD

**Issue by ntolley** [jonescompneurolab/hnn-core#239]
I was working on reproducing some of the Alpha/Beta tutorial from HNN GUI and came across a rather obvious discrepancy. Here is the dipole output from the GUI: 

![image](https://user-images.githubusercontent.com/55253912/103236570-3a860500-4913-11eb-889a-9ee065bbc7cb.png)

And here is the dipole from hnn-core:

![image](https://user-images.githubusercontent.com/55253912/103236503-1296a180-4913-11eb-900c-76319cbe582a.png)

Both simulations were run using the AlphaAndBeta.param file. Unlike HNN-GUI, this param file induces spiking in hnn-core leading to the dramatic differences in the aggregate current dipole.

I'll be digging a little deeper to figure out where the mismatch is occurring. As @cjayb has mentioned we can't always rely on HNN GUI as the "gold standard", but a gross mismatch like this indicates a deeper issue to me.

**Comment by jasmainak** [comment]
yes, this seems wrong. Is there some place where the T=-1 trick is being used? I've seen this kind of issue with that.

**Comment by ntolley** [comment]
Are you referring to the tonic input parameters like `Itonic_T_L2Pyr_soma`, or the start time of the inputs like `t0_input_dist`?

**Comment by jasmainak** [comment]
I was thinking of parameters [like these](https://github.com/jonescompneurolab/hnn/blob/master/param/AlphaAndBeta.param#L214). Is that the file you're using?

**Comment by jasmainak** [comment]
any luck here @ntolley ?

**Comment by ntolley** [comment]
Not quite yet. I am about to test parameter inference on beta events with the new API. I imagine that will help shed some light on what's going on here.

**Comment by jasmainak** [comment]
should I tag this for 0.1 release or 0.2?

**Comment by rythorpe** [comment]
FYI @ntolley I think I unknowingly encountered this bug (or parameter discrepancy between HNN and hnn-core) when I was trying to validate consistent seeding across HNN and hnn-core. Whatever the problem is, as soon as we figure this out, I think #113 will become much easier to resolve.

**Comment by ntolley** [comment]
Looks like the most recent PR's had an impact on this issue, here is what the output from the same parameter file looks like now:
![image](https://user-images.githubusercontent.com/55253912/105097385-7c1f5100-5a76-11eb-8a07-60fea8f4a358.png)

**Comment by cjayb** [comment]
I don’t get it... Could you upload the precise param-file you’re using? I get GUI-parity results with ‘AlphaAndBeta.param’ (will send screenshots tomorrow)

**Comment by cjayb** [comment]
This works for me on `master`:

```python
params_fname = op.join(hnn_core_root, 'param', 'default.param')
params = read_params(params_fname)
params['tstop'] = 710.0
params['dipole_smooth_win'] = 0  # do not smooth the dipole time courses

net = Network(params)

location = 'proximal'
burst_std = 20
weights_ampa_p = {'L2_basket': 0., 'L2_pyramidal': 5.4e-5,
                  'L5_basket': 0., 'L5_pyramidal': 5.4e-5}
syn_delays_p = {'L2_basket': 0.1, 'L2_pyramidal': 0.1,
                'L5_basket': 1., 'L5_pyramidal': 1.}

net.add_bursty_drive(
    'beta_prox', tstart=50., burst_rate=10, burst_std=burst_std, numspikes=2,
    spike_isi=10, repeats=10, location=location, weights_ampa=weights_ampa_p,
    synaptic_delays=syn_delays_p, seedcore=13)

location = 'distal'
burst_std = 20
weights_ampa_d = {'L2_basket': 0., 'L2_pyramidal': 5.4e-5,
                  'L5_pyramidal': 5.4e-5}
syn_delays_d = {'L2_basket': 5., 'L2_pyramidal': 5.,
                'L5_basket': 5., 'L5_pyramidal': 5.}
net.add_bursty_drive(
    'beta_dist', tstart=50., burst_rate=10, burst_std=burst_std, numspikes=2,
    spike_isi=10, repeats=10, location=location, weights_ampa=weights_ampa_d,
    synaptic_delays=syn_delays_d, seedcore=14)

with MPIBackend(n_procs=4):
    dpls_beta = simulate_dipole(net, n_trials=1)

fig, axes = plt.subplots(2, 1, sharex=True, figsize=(6, 8))
net.cell_response.plot_spikes_hist(ax=axes[0],
                                   spike_types=['beta_prox', 'beta_dist'])
plot_dipole(dpls_beta, ax=axes[1], layer='agg', show=False)
```

<img width="533" alt="Screenshot 2021-01-20 at 16 01 37" src="https://user-images.githubusercontent.com/5610076/105193390-c9fc8d80-5b38-11eb-9b48-3d8a7fddfb7c.png">

**Comment by ntolley** [comment]
Huge brain fart on my end, I did not set the `add_drives_from_params` in the most recent figure. I am now able to replicate the tutorial results.

I am loading `AlphaAndBeta.param` directly from a cloned HNN-GUI repo so the original discrepancy was somehow resolved in a commit between now and then. I'm a little concerned that the rhythmic drives were unknowingly broken in a previous version of master, but the issue seems to have been resolved (along with the other alpha/beta examples) so I am closing for now.

I may run a `git bisect` to try and narrow down the commit that fixed this issue. 

Thanks for the help @cjayb!

**Comment by jasmainak** [comment]
let's add this code as an example? What do you think?

**Comment by cjayb** [comment]
@ntolley no worries, API changes are a nightmare ;)

@jasmainak I agree something like the above could be added to the "alpha" example (which would then need to be renamed to "alpha_beta", I suppose). Note that the code can be further simplified by omitting the zero `*_basket` weights and corresponding delays. This is a canonical example of two 10 Hz drives producing bursts of 20 Hz signal, so I propose either a PSD or TFR, or both. This is very close to Sherman (2016) and Law (2019), which I've played around with [here](https://raw.githubusercontent.com/cjayb/hnn-core-examples/main/somatosensory_beta/simulate_law2019.py)---feel free to copy anything of interest when updating the "alpha" example!

**Comment by ntolley** [comment]
Sounds good to me! I'll open a PR today/tomorrow with the alpha example updates

**Comment by jasmainak** [comment]
excellent, looking forward to it!

**Comment by jasmainak** [comment]
> Huge brain fart on my end, I did not set the add_drives_from_params in the most recent figure. I am now able to replicate the tutorial results.

I stumbled upon the same issue today myself. @cjayb could we perhaps raise a warning when running a simulation with no input drives? And telling users that they must add the drives manually or use `add_drives_from_params=True`. If they use `add_drives_from_params=True`, a big fat deprecation warning should be raised.

**Comment by jasmainak** [comment]
Another backwards compatibility issue: perhaps we could not add a drive if in the param file t0 of drive > tstop of simulation. Maybe throw a warning to users asking them to remove the params related to this drive (naming them in the warning) if they don't want to see this warning?

**Comment by rythorpe** [comment]
> Another backwards compatibility issue: perhaps we could not add a drive to `net.external_drives` if in the param file t0 of drive > tstop of simulation?

I'm all for throwing warnings here, but I don't think we should filter what gets added to `net.external_drives` on the basis of timing. The items in `net.external_drives` should map 1-to-1 with whatever is specified by a param file or the user via calls to `net.add_...` so that we don't end up silently loosing track of network drives, gids, etc.

> Maybe throw a warning to users asking them to remove the params related to this drive (naming them in the warning) if they don't want to see this warning?

+100
