### ISSUE TITLE
plot_spikes_raster() error when no spikes occur

### ISSUE THREAD

**Issue by ntolley** [jonescompneurolab/hnn-core#240]
I can handle this if needed (since I wrote the function) but I figured this is a nice "good first issue" candidate. 

At the moment `cell_response.plot_spikes_raster()` raises an error if no spikes occur during the simulation:

![image](https://user-images.githubusercontent.com/55253912/103240577-b76aac00-491e-11eb-9dba-2a319de6f0e2.png)

The fix would entail catching simulations with no spikes, and returning an empty list. Perhaps a warning would be nice as well notifying the user why their raster plot is empty.

**Comment by jasmainak** [comment]
I would say, go for it. We already have many "good first issues".

all this is great, it means hnn_core is becoming more and more stable with each issue fixed
