### ISSUE TITLE
error when installing hnn-core

### ISSUE THREAD

**Issue by stephanie-r-jones** [jonescompneurolab/hnn-core#256]
When testing if hnn_core installed properly with  'python -c 'import hnn_core', I received the following error: 

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Applications/anaconda/lib/python3.6/site-packages/hnn_core/__init__.py", line 5, in <module>
    from .pyramidal import L2Pyr, L5Pyr
  File "/Applications/anaconda/lib/python3.6/site-packages/hnn_core/pyramidal.py", line 8, in <module>
    from neuron import h
ModuleNotFoundError: No module named 'neuron'

**Comment by jasmainak** [comment]
Hi Stephanie -- did you install Neuron first? You can do:

```py
$ pip install NEURON
```

**Comment by jasmainak** [comment]
We'll actually make it so that `NEURON` is installed automatically as part of `hnn-core` installation. It's in #255 . But let us know if this fixes the problem for you or you face other issues!

**Comment by stephanie-r-jones** [comment]
Hi Mainak, 
Yes, I intalled the latest version of NEURON and ran a test simulation through the NEURO GUI. it worked.

**Comment by stephanie-r-jones** [comment]
And, NEURON wasn't installed automatically because I had an older version of NEURON that needed to first be removed

**Comment by stephanie-r-jones** [comment]
When I say it worked, I mean NEURON works, not hnn_core.. still issue there

**Comment by jasmainak** [comment]
how did you install NEURON? Did you use `pip` as I suggested above or you downloaded and installed it with the installer?

**Comment by stephanie-r-jones** [comment]
pip didn't automatically work so I used the installer... should I reinstall and try again?

**Comment by stephanie-r-jones** [comment]
I mean uninstall and try again

**Comment by jasmainak** [comment]
I think `pip` should be the preferred way. I have stopped using the installer for a while. What issue did you face with `pip` ?

**Comment by stephanie-r-jones** [comment]
Uninstalling NEURON, and then reinstalling NEURON with pip worked. Note, I first tried to just run pip install https://api.github.com/repos/jonescompneurolab/hnn-core/zipball/master  and this did not install NEURON, and I think you are suggesting it should have?

**Comment by jasmainak** [comment]
If you open `ipython` and then do:

```sh
$ ipython
```

and then:

```py
>>> import neuron
```

does this work? If not, I think you can safely run that `pip` command. No need to uninstall anything. It's possible that for the GUI, NEURON is installed in a different environment.

**Comment by jasmainak** [comment]
> Note, I first tried to just run pip install https://api.github.com/repos/jonescompneurolab/hnn-core/zipball/master and this did not install NEURON

Yes, this is something to fix. We're working on it in #255 . It should really install everything with a single command but currently it doesn't. You have to install `NEURON` separately first

**Comment by stephanie-r-jones** [comment]
Also, installing hnn_core has broken my HNN GUI docker installation. I'm going to try now the pip install of HNN GUI and see how the goes...
