### ISSUE TITLE
plot_simulate_evoked.py example is giving an error 

### ISSUE THREAD

**Issue by stephanie-r-jones** [jonescompneurolab/hnn-core#258]
1) I think it would be helpful to write on top of all the example tutorials that they are automatically 
distributed in the folder hnn_core/examples 

2) The image that pops up when running this example is 
<img width="636" alt="Screen Shot 2021-01-24 at 12 58 29 PM" src="https://user-images.githubusercontent.com/19916105/105639176-bdcc4500-5e44-11eb-9bb6-c6397487f714.png">

And the following error message came up: 

joblib will run over 1 jobs
dlopen failed - 
dlopen(/Applications/anaconda/lib/python3.6/site-packages/hnn_core/mod/x86_64/.libs/libnrnmech.so, 2): Library not loaded: /Applications/NEURON-7.5/nrn/x86_64/lib/libnrnoc.0.dylib
  Referenced from: /Applications/anaconda/lib/python3.6/site-packages/hnn_core/mod/x86_64/.libs/libnrnmech.so
  Reason: image not found
Loading custom mechanism files from /Applications/anaconda/lib/python3.6/site-packages/hnn_core/mod/x86_64/.libs/libnrnmech.so
Traceback (most recent call last):
  File "plot_simulate_evoked.py", line 49, in <module>
    dpls = simulate_dipole(net, n_trials=2)
  File "/Applications/anaconda/lib/python3.6/site-packages/hnn_core/dipole.py", line 71, in simulate_dipole
    dpls = _BACKEND.simulate(net, n_trials, postproc)
  File "/Applications/anaconda/lib/python3.6/site-packages/hnn_core/parallel_backends.py", line 166, in simulate
    sim_data = parallel(myfunc(net, idx) for idx in range(n_trials))
  File "/Applications/anaconda/lib/python3.6/site-packages/hnn_core/parallel_backends.py", line 166, in <genexpr>
    sim_data = parallel(myfunc(net, idx) for idx in range(n_trials))
  File "/Applications/anaconda/lib/python3.6/site-packages/hnn_core/parallel_backends.py", line 34, in _clone_and_simulate
    neuron_net = NetworkBuilder(net, trial_idx=trial_idx)
  File "/Applications/anaconda/lib/python3.6/site-packages/hnn_core/network_builder.py", line 276, in __init__
    self._build()
  File "/Applications/anaconda/lib/python3.6/site-packages/hnn_core/network_builder.py", line 284, in _build
    load_custom_mechanisms()
  File "/Applications/anaconda/lib/python3.6/site-packages/hnn_core/network_builder.py", line 147, in load_custom_mechanisms
    raise ValueError('The custom mechanisms could not be loaded')
ValueError: The custom mechanisms could not be loaded

**Comment by stephanie-r-jones** [comment]
I'm actually getting this error with all the examples that I try to run? Perhaps NEURON did not install properly?

**Comment by jasmainak** [comment]
humm ... for whatever reason, the custom mechanism didn't get compiled I think. The installation should throw an error if this happens. If you do:

```sh
$ ls /Applications/anaconda/lib/python3.6/site-packages/hnn_core/mod/
```

what do you see? Ideally, there should be this file:

`/Applications/anaconda/lib/python3.6/site-packages/hnn_core/mod/x86_64/.libs/libnrnmech.so`

are there no files at all? Or there are some files but named differently?

Thanks for testing this far. We'll work on fixing these issues and let you know when to try again!

**Comment by stephanie-r-jones** [comment]
Yes, I see libnrmech.so .. here's an image of everything in the directory 
<img width="945" alt="Screen Shot 2021-01-24 at 5 54 48 PM" src="https://user-images.githubusercontent.com/19916105/105646332-69898b00-5e6d-11eb-8a53-8b05c808d35d.png">

**Comment by jasmainak** [comment]
strange ... so the compilation did work

what I don't understand is why you see this message:

> Library not loaded: /Applications/NEURON-7.5/nrn/x86_64/lib/libnrnoc.0.dylib

the [latest version](https://pypi.org/project/NEURON/) of NEURON on pypi is actually 7.8.2, not 7.5. It could be that these files you see are from your first attempt at installing hnn-core with the old NEURON. Could you remove this folder altogether

```sh
$ rm -rf /Applications/anaconda/lib/python3.6/site-packages/hnn_core/
```

and try again to do:

```sh
$ pip install --upgrade https://api.github.com/repos/jonescompneurolab/hnn-core/zipball/master
```
?

You can check the version of NEURON by doing:

```sh
$ pip list | grep NEURON
```

**Comment by stephanie-r-jones** [comment]
7.5 was the last version of NEURON that I had that I tried to uninstall but I don't think it actually uninstalled.. eventhough it is now in the trash . Any suggestions on how I can make sure 7.5 is removed from my computer and I'll try to reinstall NEURON again.

**Comment by jasmainak** [comment]
I think you uninstalled it just fine. You can check with this command:

```py
$ pip list | grep NEURON
```

But you need to install again `hnn-core` with the new version of NEURON.

**Comment by stephanie-r-jones** [comment]
I have the most up to date version of NEURON . 
I removed and reinstalled hnn_core. 
However, now I can seemed to find the examples folder? When I installed hnn_core the first time there was a folder in my home folder named hnn_core and an examples folder in here. Now I only see hnn_core in /Applications/anaconda/lib/python3.6/site-packages/hnn_core  
There is no examples file in this directory? did I download something else last time?

**Comment by stephanie-r-jones** [comment]
I now think I have everything up and running??? However, when I run the plot_simulate_evoked.py example, it seems to be running without end? I get a figure of the cell grid but nothing else. The terminal output all of the parameters and nothing else and seems to be still running after 5 minutes?

**Comment by jasmainak** [comment]
okay, so what you had before was download of the entire github repository. That's what you need for a developer install. But now you're doing the user installation. In this set up, the folder is copied into /Applications/anaconda/lib/python3.6/site-packages/ and is commonly not supposed to be edited by the user. So what you see is completely expected I would say

To run the example, you can go to [one of the examples](https://jonescompneurolab.github.io/hnn-core/auto_examples/index.html) on the website, scroll to the bottom of the page and download the .py file

**Comment by stephanie-r-jones** [comment]
See comment above about issues with the example file. 
In regard to developer vs user install.. I just followed the instructions on the website both time. Why would one give me the developer install with the entire repository and one the user?

**Comment by jasmainak** [comment]
The instructions for the developer install is here: https://github.com/jonescompneurolab/hnn-core/blob/master/CONTRIBUTING.rst. It's not the same, are you sure you followed the same instructions last time? :)

Also what do you see as the last output? Do you see something like this:

```py
joblib will run over 1 jobs
Loading custom mechanism files from /Users/mainak/Documents/github_repos/hnn-core/hnn_core/mod/x86_64/.libs/libnrnmech.so
Building the NEURON model
[Done]
running trial 1 on 1 cores
Simulation time: 0.03 ms...
Simulation time: 10.0 ms...
```

the errors you have are totally novel :)

**Comment by stephanie-r-jones** [comment]
![Screen Shot 2021-01-25 at 10 30 43 AM](https://user-images.githubusercontent.com/19916105/105726780-6f787e00-5ef8-11eb-92de-2bdea1d16f06.png)
Ok. I must have downloaded the developer install sometimes ago to help with the documentation... 

In the last run I did not see that output, rather just a list of the parameters then nothing...

**Comment by jasmainak** [comment]
I think you need to close the figure for the rest of the script to run if you use python scripts like that. I'd actually recommend doing:

```sh
$ ipython --matplotlib
```

and then 

```py
%run plot_simulate_evoked.py
```

inside ipython. So you have access to the variables and everything just like Matlab

**Comment by jasmainak** [comment]
reopening so @stephanie-r-jones can confirm if the solution above worked.

**Comment by stephanie-r-jones** [comment]
ok. It worked when I close each window that opened. This is indeed a weird way to run it. It also worked perfectly fine when I ran $ipython --matplotlib 
$run plot_simulate_evoked.py 

It is probably worth noting these issues somewhere in the instructions. 

Also, in the plot of the spiking, the activity in the layer 5 cells is on graphically on top of the layer 2/3 activity. this is non-intutitive because physically layer 2/3 is on top of layer 5. I suggest swapping them as in the HNN GUI.

**Comment by stephanie-r-jones** [comment]
Lastly, this simulation seems to be much slower than it is in the HNN GUI? Has a comparison of the time to run in each been made? What is the difference?

**Comment by jasmainak** [comment]
> It is probably worth noting these issues somewhere in the instructions.

@cjayb read your thoughts and made a PR to fix it. Now we have a section here:
https://jonescompneurolab.github.io/hnn-core/#documentation-and-examples :)

> Also, in the plot of the spiking, the activity in the layer 5 cells is on graphically on top of the layer 2/3 activity. this is non-intutitive because physically layer 2/3 is on top of layer 5. I suggest swapping them as in the HNN GUI.

great point! I think @ntolley is the expert to fix this

> Lastly, this simulation seems to be much slower than it is in the HNN GUI? Has a comparison of the time to run in each been made? What is the difference?

yep, it's much slower. You can install the MPI backend if you want GUI-like performance. See: https://jonescompneurolab.github.io/hnn-core/parallel.html. However, it can be a bit tricky to install ... if you feel like an adventure :) IMO, it doesn't matter if something is 30 seconds vs 1 minute 30 seconds. Ultimately both are non-interactive. Power users can install the MPI backend though. That option exists!

also regarding comparison time -- if you run 4 trials in parallel (Joblibs) vs 4 trials with each trial in parallel across neurons (MPI), I think MPI option would win but not by much (probably a 10 seconds). Blake ran some comparisons but I don't think a proper benchmark has ever been made. Note that GUI by default uses all the cores on your laptop, that's why it's faster.

**Comment by jasmainak** [comment]
I think all the issues mentioned here have already been fixed
