### ISSUE TITLE
make all use of post-processing for plotting explicit (ignore params)

### ISSUE THREAD

**Issue by cjayb** [jonescompneurolab/hnn-core#262]
`param`-files contain fields related to the way results should be visualised. We should ignore these, and instead make them explicit in our examples (and document in the API calls, of course). The list includes (please add!):

- `dipole_scalefctr`
- `dipole_smooth_win`
- `f_max_spec` (irrelevant)
- others?

**Comment by jasmainak** [comment]
`tstop` should go into `simulate_dipole` !
