### ISSUE TITLE
Cleanup visualisation code prior to 0.1 release

### ISSUE THREAD

**Issue by cjayb** [jonescompneurolab/hnn-core#265]
I strongly suggest we make decisions on these points before releasing. I fear they'll haunt us otherwise!

- [x] to `baseline_renormalize` or not (a.k.a. `postproc=What`) (see #270; deferred to 0.2)
- [x] decide on and implement a principled way to handle units, esp. when plotting (done in #264; units are nAm)

~On the first point, I propose changing to `postproc=False` (and modifying all tests to explicitly set it to `True`). I think this should be the case regardless of what the default behaviour of HNN GUI needs to be.~

~On the second, I like @jasmainak 's proposal to keep everything in fAm, and use `scalings`-arguments to plot in given units. @rythorpe also pointed out that legends can be used to indicate what amount of scaling has been applied.~

These seem like two quite straightforward PRs to me, should we include them in 0.1?

**Comment by jasmainak** [comment]
I am okay with this but we might need a section in the documentation to explain how to get the "old behavior" and explaining to folks what has changed and why. It's partly there in the whats_new but maybe worth pulling it out into a separate document might be helpful. Mostly to get buy-in from folks who have been using HNN-GUI in the past.

For postproc, another option is to set `postproc=True` but have a deprecation warning that next cycle it will become `postproc=False`. But probably not worth the effort

**Comment by ntolley** [comment]
This may not be worth taking the time to implement but the [quantities](https://python-quantities.readthedocs.io/en/latest/) package is definitely aimed at this exact issue of units.

I've seen it implemented in a few neuroscience specific toolkits (neo and elephant specifically), but at the moment it is tough to say how many headaches it would save.
