### ISSUE TITLE
raise warning when no external drives added

### ISSUE THREAD

**Issue by cjayb** [jonescompneurolab/hnn-core#269]
> @cjayb could we perhaps raise a warning when running a simulation with no input drives? And telling users that they must add the drives manually or use add_drives_from_params=True. If they use add_drives_from_params=True, a big fat deprecation warning should be raised.

+1 on both counts. 

> perhaps we could not add a drive to net.external_drives if in the param file t0 of drive > tstop of simulation?

and

> The items in net.external_drives should map 1-to-1 with whatever is specified by a param file or the user via calls to net.add_... so that we don't end up silently loosing track of network drives, gids, etc.

I propose raising a `ValueError` for drives (from params or otherwise) where `t0 > T`. The solution is either to fix the param-file (setting weights to zero effectively "removes" the drive), or, preferably, use the new API.

**Comment by jasmainak** [comment]
> I propose raising a ValueError for drives (from params or otherwise) where t0 > T

I think we agreed in #397 that we'll truncate rather than raise an error?

The warning is easy to tackle?

I'm trying to look at low hanging fruits from 0.2 milestone and get them done to prepare for a release

**Comment by jasmainak** [comment]
probably easily bunched with #410 ?

**Comment by cjayb** [comment]
Right, now that `tstop` is a parameter of the simulation, the `t0` of the drives should be allowed to be arbitrary. Perhaps a `RuntimeError` if `simulate_dipole` is called on a `net` without drives?

**Comment by jasmainak** [comment]
yeah that sounds good. Not sure if we want an error or warning ... I remember @ntolley saying there were situations where you'd want to simulate a network without driving it

**Comment by ntolley** [comment]
Close issue? I think we've moved towards the opinion that less warnings is good, but maybe this one is worth it.
