### ISSUE TITLE
Network object memory leak?

### ISSUE THREAD

**Issue by blakecaldwell** [jonescompneurolab/hnn-core#290]
I noticed that the `Network` object grows in size after successive simulations without reinitialization. Object size including references is reflected in the size when pickled:
```
Trial (0) network size: 94537
MPI will run over 8 processes
Running 1 trials...
```

```
Trial (19) network size: 205557
MPI will run over 8 processes
Running 1 trials...
```

Gist:
https://gist.github.com/blakecaldwell/2aea9e5eb888db4f564a9ec9e7b72c04

It seems important to keep the overall Network object small since it is being passed around to run simulations.

**Comment by blakecaldwell** [comment]
Leak is even worse when `add_drives_from_params=True`. The object grows 10x after 5 trials.

**Comment by cjayb** [comment]
Thanks @blakecaldwell , I think I localised the problem and fixed it in #291 (let me know...)

**Comment by cjayb** [comment]
> It seems important to keep the overall Network object small since it is being passed around to run simulations

Could you elaborate on this a bit? At what stage would this become a bottleneck? I ask because #276 is increasing the size of `net` from 317kB  to 14.5MB (both are with drives and cell responses). In relation to the total time a simulation runs, how worried should we be of the added overhead in broadcasting the `net` to the ranks?

**Comment by blakecaldwell** [comment]
> Could you elaborate on this a bit? At what stage would this become a bottleneck? I ask because #276 is increasing the size of `net` from 317kB to 14.5MB (both are with drives and cell responses). In relation to the total time a simulation runs, how worried should we be of the added overhead in broadcasting the `net` to the ranks?

That's significant. The simulation time can be reduced to a few seconds with enough cores. Sending the network could take several times longer than simulation runtime: it could be 10+ seconds, maybe even a minute?

A plea for only passing `params` to MPI simulations?

**Comment by jasmainak** [comment]
what's the usecase for sending the network several times? I think this is a one-time cost?

Let's do some benchmarks with `timeit` if we're really worried about it

**Comment by cjayb** [comment]
I used modified `mpi_child.py` to use `time.perf_counter()`:

```python
        with MPISimulation() as mpi_sim:
            tic = time.perf_counter()
            net = mpi_sim._read_net()
            toc = time.perf_counter()
            with open(f'rank{mpi_sim.rank}.txt', 'wt') as fp:
                fp.write(f'Rank {mpi_sim.rank} read net in {toc - tic} seconds\n')
            sim_data = mpi_sim.run(net)
            tic = time.perf_counter()
            with open(f'rank{mpi_sim.rank}.txt', 'at') as fp:
                fp.write(f'Rank {mpi_sim.rank} simulated net in {tic - toc} seconds\n')
            mpi_sim._write_data_stderr(sim_data
```

I used the `default` net with `add_drives_from_params=True`. The results **for this branch (290)** are:

```bash
Rank 0 read net in 0.530793663 seconds
Rank 0 simulated net in 14.232586563 seconds
Rank 1 read net in 1.0709857980000002 seconds
Rank 1 simulated net in 13.682690771999999 seconds
Rank 3 read net in 1.062523908 seconds
Rank 3 simulated net in 13.686804667999999 seconds
Rank 2 read net in 1.066428757 seconds
Rank 2 simulated net in 13.685555247 seconds
Rank 6 read net in 1.082483644 seconds
Rank 6 simulated net in 13.669445983 seconds
Rank 7 read net in 1.071619755 seconds
Rank 7 simulated net in 13.683248594 seconds
Rank 5 read net in 1.0686847959999999 seconds
Rank 5 simulated net in 13.675559048 seconds
Rank 4 read net in 1.055470449 seconds
Rank 4 simulated net in 13.696048599000001 seconds
```

The results **for PR 276** are:

```bash
Rank 0 read net in 4.48996908 seconds
Rank 0 simulated net in 14.595200889000001 seconds
Rank 1 read net in 4.958184565 seconds
Rank 1 simulated net in 14.111261745 seconds
Rank 3 read net in 4.963383182 seconds
Rank 3 simulated net in 14.110378454 seconds
Rank 2 read net in 4.95441973 seconds
Rank 2 simulated net in 14.118473186 seconds
Rank 6 read net in 4.955038174 seconds
Rank 6 simulated net in 14.116642953 seconds
Rank 7 read net in 4.95228918 seconds
Rank 7 simulated net in 14.118506573000001 seconds
Rank 5 read net in 4.951824761 seconds
Rank 5 simulated net in 14.119489788000001 seconds
Rank 4 read net in 5.004722618 seconds
Rank 4 simulated net in 14.071160010000002 seconds
```

So that's a factor of 5 increase in broadcast-time, or going from 1/15th to 5/19th of the total simulation time (from 6 to 26%) for this network.

This is on my local machine. Presumably on a multi-node cluster that could be a lot worse (even on infiniband). Is that what you mean by "maybe a minute"? A longer simulation wouldn't increase the broadcast-time, only the simulation itself.

**Not** passing `params` around is actually a principled design choice, which we're not easily going to let go of! That being said, I am concerned that a bloated `net` is going to hurt us down the road.

@blakecaldwell can you confirm that the memory leak is no longer an issue? Are you still getting the periodic segfaults?

**Comment by jasmainak** [comment]
half a second is acceptable to me!

**Comment by jasmainak** [comment]
we had the idea of adding a test in #161 . I think that issue is still up for grabs!

**Comment by blakecaldwell** [comment]
> what's the usecase for sending the network several times? I think this is a one-time cost?

Optimization

**Comment by blakecaldwell** [comment]
> half a second is acceptable to me!

I think the overhead is 4 seconds. "simulated net in" does not appear to `include _read_net`.

So I realized my idea of 10+ seconds is coming from the code I am currently working on modeled after using `Queue` like how MNE does it. The change in #287 is making the timing above pretty reasonable.

There's a likely performance regression to using `Queue`, but that's a topic for the upcoming PR.

**Comment by blakecaldwell** [comment]
> @blakecaldwell can you confirm that the memory leak is no longer an issue? Are you still getting the periodic segfaults?

Yes to fixing the memory leak. Still trying to get the above-mentioned `Queue` code ready for a PR, along with testing for the segfault.

**Comment by cjayb** [comment]
I rebooted and rebased by branch of 276 to include 287. The increase in broadcast overhead is about 3 seconds (going from master to #276). I modified the values in the above post accordingly.

**Comment by blakecaldwell** [comment]
> There's a likely performance regression to using `Queue`, but that's a topic for the upcoming PR.

Turns out the `Queue` isn't slower. Anyway, I think all of my estimates were off. I was mistaken when I thought it could take a minute.

> This is on my local machine. Presumably on a multi-node cluster that could be a lot worse (even on infiniband). Is that what you mean by "maybe a minute"? A longer simulation wouldn't increase the broadcast-time, only the simulation itself.

Even 3 seconds for passing around data is significant when the entire simulation takes 3 seconds. Yes, it will stay at 3 seconds. I just mean it becomes a 100% relative overhead vs. a smaller percentage on our laptops.
