### ISSUE TITLE
Function to visualize cell-cell and drive-cell connectivity. 

### ISSUE THREAD

**Issue by ntolley** [jonescompneurolab/hnn-core#292]
Working on the connectivity API made it apparent how useful it will be to visualize the cell-cell and drive-cell connectivity. I think the simplest implementation would be along the lines of `plt.imshow()` with arguments that specify which receptors/synapses are displayed.

**Comment by jasmainak** [comment]
close issue @ntolley ?

**Comment by jasmainak** [comment]
@ntolley shouldn't the connectivity plot also show the weight of the connection along with a colorbar? So you can visualize the `lamtha` ?

**Comment by ntolley** [comment]
Definitely agree. I'll either make that it's own PR or append it to the PR that creates Gaussian decaying connection probabilities, whichever one I start first.

I'm still fond of the binary connection visualization so I'll add an argument that switches the view, perhaps
```py
net.connectivity[idx].plot(weight=True)
```

**Comment by jasmainak** [comment]
humm ... if you think the plotting method should live in `connectivity` it's best to modify that data structure so it stores the weights. Not sure how much of a performance impact that would be? Easier is to move the `plot` method to `Network` so you have `net.plot_connectivity`.

By the way, I noticed that the connectivity plotting function is not listed here:

https://jonescompneurolab.github.io/hnn-core/dev/api.html#visualization-hnn-core-viz

don't forget to add it there while you're at it!

**Comment by jasmainak** [comment]
@ntolley anything left to do here?

**Comment by ntolley** [comment]
No I think we've covered our bases for visualizing new connections (in two different ways!) Happy to close.
