### ISSUE TITLE
change the legend of "simulate dipole for evoked inputs example"

### ISSUE THREAD

**Issue by stephanie-r-jones** [jonescompneurolab/hnn-core#302]
A minor comment: on the  hnn-core examples page I suggest changing the legend name for the first evoked response example 01. from "Simulate dipole for evoked inputs" to "Simulate an evoked potential", which matches the wording on the HNN tutorials page.

**Comment by rythorpe** [comment]
I'm pretty sure this has already been fixed. Shown below is a screen shot from the tutorials page (v0.2) showing the thumbnail caption for the ERP tutorial that matches the [HNN-GUI tutorial](https://jonescompneurolab.github.io/hnn-tutorials/erp/erp). Feel free to reopen this issue if I've misunderstood.
![image](https://user-images.githubusercontent.com/20212206/173864768-68fa44e0-01b2-449e-ad2e-c1950dd008f4.png)
