### ISSUE TITLE
Opaque exception on creating bursty inputs. Clarify where default cycle_events_isi of 10 came from

### ISSUE THREAD

**Issue by blakecaldwell** [jonescompneurolab/hnn-core#303]
From https://github.com/jonescompneurolab/hnn/issues/178

I got the exception below using the parameter file in the issue:
```
Starting simulation (8 cores). . .
Traceback (most recent call last):
  File "/Users/blake/repos/hnn/hnn/qt_thread.py", line 237, in run
    self._run(banner=banner, sim_length=sim_length)  # run simulation
  File "/Users/blake/repos/hnn/hnn/qt_thread.py", line 265, in _run
    net = Network(sim_params, add_drives_from_params=True)
  File "/Users/blake/repos/hnn-core/hnn_core/network.py", line 253, in __init__
    _add_drives_from_params(self)
  File "/Users/blake/repos/hnn-core/hnn_core/drives.py", line 144, in _add_drives_from_params
    net._instantiate_drives(n_trials=net.params['N_trials'])
  File "/Users/blake/repos/hnn-core/hnn_core/network.py", line 714, in _instantiate_drives
    seedcore=drive['seedcore'])
  File "/Users/blake/repos/hnn-core/hnn_core/drives.py", line 263, in _drive_cell_event_times
    prng2=prng2)
  File "/Users/blake/repos/hnn-core/hnn_core/drives.py", line 500, in _create_bursty_input
    raise ValueError('Burst duration cannot be greater than period')
ValueError: Burst duration cannot be greater than period
```

The parameter file specified `params['events_per_cycle_prox']` of 60, which has to be reduced to 5 in order to run. This is because the default `cycle_events_isi` passed to `_create_bursty_input()` is 10ms. If this is a reasonable assumption, maybe include that in the exception so that the user can figure out how to change the parameter file accordingly.

**Comment by cjayb** [comment]
Which parameter file was that? And what was the burst frequency? I think the exception could (should be clearer), but 60 events per cycle seems like a lot (for our usual <1 s simulations). The HNN GUI doesn't allow changing the ISI, right? The 10 ms was chosen as default because it was hard-coded into the old code.

**Comment by jasmainak** [comment]
It's usually good practice to say what values we got in the error message, so that the user can figure out what went wrong. E.g.:

```sh
Burst duration  (got 10 s) cannot be greater than period (got 5 s).
```

making it a little more informative would definitely help

**Comment by blakecaldwell** [comment]
Parameter file is in the linked issue. Yeah, not I'm debating parameter choice.
