### ISSUE TITLE
no way to modify cell properties

### ISSUE THREAD

**Issue by rythorpe** [jonescompneurolab/hnn-core#316]
There is currently no mechanism for even an advanced user to set cell properties (e.g., GABAA decay time as demonstrated in the [gamma tutorial](https://jonescompneurolab.github.io/hnn-tutorials/gamma/gamma)). All cell properties are set to the default values within each cell instance when `network_builder._build()` calls `_create_cells_and_drives()`.

A short-term solution would be to set `override_params` when `_create_cells_and_drives()` instantiates its cell objects. Advanced users (or hnn-gui) can change cell properties in the `Params` dict.

**Comment by rythorpe** [comment]
Actually, my proposed fix might not make sense after #310. We'll need to implement this in our API.

**Comment by jasmainak** [comment]
By cell properties, you mean the biophysics?

Is there a realistic use for modifying the geometry right now with the default network. I'm not even sure you would get "correct" results if you modified them.

I suggest chalking out a few options for setting the biophysics. I'm just throwing one out to get the ball rolling:

```py
net.set_cell_biophysics(celltype='L5_pyramidal', section='soma', mechanism='ca', property='gbar')
```

**Comment by ntolley** [comment]
> Is there a realistic use for modifying the geometry right now with the default network.

Dendrite morphology would be a valid use, but this seems more like an HNN-netpyne issue. I'd definitely like to understand how much complex branching patterns impact dendritic integration, but I'm unaware of good intermediates between the current level of detail, and true dendrite morphology.

**Comment by jasmainak** [comment]
right, but I guess I'm asking in terms of existing functionality in HNN ... there are all these parameters that allow changing length and diameter of sections. Does anyone ever tweak them?

**Comment by ntolley** [comment]
None that I'm aware of currently, but I just thought of a really simple use case that would be important for estimating dipole scaling. Currently the default is a model for S1, but cortical thickness is known to vary across regions: https://www.pnas.org/content/97/20/11050

For anyone trying to accurately estimate the size of the network necessary to produce the dipole fluctuations they record, cortical thickness would be important to account for. 

I think diameter is getting back into problems of detailed morphology as I am unaware of systematic variations (that are important for this level abstraction). However, length definitely seems fair game.

**Comment by stephanie-r-jones** [comment]
One thing to be aware of is that the firing properties of the neurons depend on the morphology. The parameters of each of the ionic channels were carefully tuned to re-create realistic spiking patterns - and most recently updated calcium dynamics - all of this would need to be retuned if the morphology of the cell changes. 

Also of note the original choice for the morphology of the pyramid neurons came from Bush and Sejnowski J. Neuroscience Methods 1993 
“Reduced compartment models of neocortical pyramidal cells”. This original paper had passive somatic and dendritic compartments. We added active currents to produce the appropriate spiking patterns to somatic injected  current. 


*******************************************
Stephanie R. Jones, PhD
Associate Professor 
Brown University 
Department of Neuroscience 
Stephanie_Jones@Brown.edu
https://sites.brown.edu/stephanie-r-jones-lab/
Human Neocortical Neurosolver
https://hnn.brown.edu <https://hnn.brown.edu/>

**Comment by jasmainak** [comment]
Let's focus on biophysics and synapses for now. If folks have the usecase of changing morphologies, we can form appropriate collaborations and think of how best to address it starting from a scientific study. I think it's not so straightforward as tweaking the length and diameter. 

Also, you should read the code in [set_geometry](https://github.com/jonescompneurolab/hnn-core/blob/master/hnn_core/pyramidal.py#L106). What I don't understand is how the "section points" can be modified independently of the section length/diameter. Something does not feel right there ...

**Comment by rythorpe** [comment]
> Let's focus on biophysics and synapses for now. If folks have the usecase of changing morphologies, we can form appropriate collaborations and think of how best to address it starting from a scientific study. I think it's not so straightforward as tweaking the length and diameter.

Sounds good!

> Also, you should read the code in [set_geometry](https://github.com/jonescompneurolab/hnn-core/blob/master/hnn_core/pyramidal.py#L106). What I don't understand is how the "section points" can be modified independently of the section length/diameter. Something does not feel right there ...

Wow this is wild. It looks like the sequence of `Pyr._get_dend_props()` -> `Pyr.create_dends()` -> `Pyr.set_geometry()` was designed to, once again, give power to the param files s.t. `p_all`  defines the geometry of each compartment. The crazy thing is that the hard-coded geometry defined in the child pyramidal cell classes only gets set [if also defined in the default parameter set](https://github.com/jonescompneurolab/hnn-core/blob/eb173119b1832be6b170c25e738b978e74f05d73/hnn_core/pyramidal.py#L168) (I think?).

According the [nrn docs](https://neuron.yale.edu/neuron/static/py_doc/modelspec/programmatic/topology/geometry.html#d-specification-of-geometry), setting section geometry preserves topology. I'm guessing this is why [length and diameter properties are defined last](https://github.com/jonescompneurolab/hnn-core/blob/eb173119b1832be6b170c25e738b978e74f05d73/hnn_core/pyramidal.py#L143-L154).

**Comment by jasmainak** [comment]
@rythorpe do you want to give this a shot? I suggest diving into the code and the right API will become clear (or not!)

**Comment by rythorpe** [comment]
> @rythorpe do you want to give this a shot? I suggest diving into the code and the right API will become clear (or not!)

Yep, I'll create a PR shortly!
