### ISSUE TITLE
constructing network object is too slow

### ISSUE THREAD

**Issue by jasmainak** [jonescompneurolab/hnn-core#317]
Try this:

```py
In [7]: %timeit Network(params)                                                 
7.16 s ± 720 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

discovered while working on ipywidget interface in #76 . I think it's related to your latest changes in connectivity @ntolley . 7 seconds is too slow. I think it should be instantaneous since there are no Neuron objects involved at this point. I will update this comment with profiling results soon. 

[Line profiler](https://github.com/pyutils/line_profiler) gives me this:

![image](https://user-images.githubusercontent.com/15852194/115132836-c6f72900-9fd1-11eb-8262-7637014f4aae.png)

Some of these validations checks are really slowing things down. Also is the `deepcopy` necessary (see example below)? Just removing that may suddenly speed things up massively

![image](https://user-images.githubusercontent.com/15852194/115132921-69171100-9fd2-11eb-92c2-26aa83f07719.png)

**Comment by ntolley** [comment]
Can you try rebasing? I agree that this could still be sped up but I added a large number of speed improving modifications to the type checks. Here is my output from timeit:
![image](https://user-images.githubusercontent.com/55253912/115162038-13447680-a06f-11eb-8ba6-ad9308761105.png)

**Comment by jasmainak** [comment]
indeed! I get:

```sh
In [2]: %timeit Network(params)                                                                                                                               
123 ms ± 16 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

after rebase. Closing issue as I can live with 123 ms :)

**Comment by jasmainak** [comment]
Thanks @ntolley !
