### ISSUE TITLE
add more details to examples

### ISSUE THREAD

**Issue by jasmainak** [jonescompneurolab/hnn-core#337]
This has come up multiple times. We need to add more narrative to the examples for folks who are beginners to the HNN framework. This would involve copying over some of the text from the tutorials

**Comment by rythorpe** [comment]
We'll need to be careful though that we don't turn our examples in tutorials as that is not their purpose. Do we have any general guidelines for how we want to distinguish between the two cases?

**Comment by jasmainak** [comment]
humm ... I'm not sure, perhaps a conversation with @stephanie-r-jones might be appropriate. Maybe start with pull requests one example at a time and get feedback from Stephanie.

**Comment by jasmainak** [comment]
My feeling is that some basic knowledge should be given, e.g., what is proximal/distal drive. For detailed rationale, they can be directed to the tutorials. Also the tutorials are longer whereas our examples are shorter and don't explore in depth exploration of parameters.

**Comment by stephanie-r-jones** [comment]
We should discuss this further as a group and lay out a plan. My initial though is that for examples that reproduce figures in the tutorials, users can be explicitly directed to read the background information on the tutorials page, and that the code in the example will reproduce Figure X in the tutorial.  Some examples will not have corresponding tutorials on the website, for example Ryan's median nerve example. I don't think we'll want to make tutorials for all examples, but maybe we could end up with something like, the code in this example will recreate Figure X  in a paper. For other examples, we might simply say. This example is constructed for users with a baseline knowledge of HNN and coding in HNN-core. To obtain this knowledge, please start with the GUI tutorials, and corresponding HNN-core examples X, Y, Z.  As Ryan suggested, we should also think about a way to convey the overall basics and workflow behind each example in HNN-core language, see for example the "overview" section of https://hnn.brown.edu/tutorials/  - can we relate these concepts to functions in HNN-core?  See also https://hnn.brown.edu/under-the-hood/ - can we relate these features to functions in HNN-core?

**Comment by jasmainak** [comment]
Also, something we implemented in MNE couple of years ago was a glossary: https://mne.tools/stable/glossary.html

I think HNN-core could also benefit from a page like that.

**Comment by jasmainak** [comment]
closing this in favor #381
