### ISSUE TITLE
CircleCI runs out of space due to large download in examples(?)

### ISSUE THREAD

**Issue by cjayb** [jonescompneurolab/hnn-core#345]
A [recent push of mine](https://app.circleci.com/pipelines/github/cjayb/hnn-core/185/workflows/f74ce822-fba7-4bb1-a668-7f3579c52098/jobs/196) died with

```python
OSError: [Errno 28] No space left on device
```

I can see the somato-example is a 500+MB download. This hasn't been an issue before, so perhaps nothing to fix?

**Comment by jasmainak** [comment]
humm ... not sure, can you make another push to see if it happens again? I couldn't restart your build because apparently I don't have the right permissions

**Comment by cjayb** [comment]
Hasn't happened again. Assume it was a fluke [`C-x M-c M-butterfly`](https://xkcd.com/378/). Closing
