### ISSUE TITLE
tonic bias signature inconsistent with other functions

### ISSUE THREAD

**Issue by jasmainak** [jonescompneurolab/hnn-core#347]
The tonic bias function has the following signature:

https://github.com/jonescompneurolab/hnn-core/blob/c65bc1e1ffa3438727e0bc699aea09aae869ec81/hnn_core/network.py#L889-L890

I think `T` should be replaced with `tstop` to be consistent with the other functions. We can still do this until 0.3 is released. Good issue for a new contributor.

**Comment by ntolley** [comment]
@kenloi this might be a good problem so you can get familiar with collaborating on github.
