### ISSUE TITLE
L5 cells are ABOVE L2 cells

### ISSUE THREAD

**Issue by cjayb** [jonescompneurolab/hnn-core#351]
Yes, that happened... No idea when, but it explains _so_ much in #329 ...

Don't believe me? Me neither, but it's been staring at us all along:

![](https://jonescompneurolab.github.io/hnn-core/dev/_images/sphx_glr_plot_simulate_evoked_001.png)

ping @jasmainak @ntolley @rythorpe

**Comment by ntolley** [comment]
Wow I swear I actually remember seeing this during our last meeting, but assumed I was wrong. Ignorance is a dangerous bliss 😄

**Comment by jasmainak** [comment]
underscores the importance of visualizing things :)
