### ISSUE TITLE
plot_cell_connectivity is hard to use

### ISSUE THREAD

**Issue by jasmainak** [jonescompneurolab/hnn-core#375]
@ntolley I was messing around with `plot_cell_connectivity` and I found it really difficult to come up with the right `src_gid` in first try. It either errored or gave me an src_gid at some place I didn't intend. What do you think of making the plot interactive? Show the grid of src_gids as well and when user clicks on it, then update the connectivity. I can give this a shot if you agree

**Comment by ntolley** [comment]
I think that would be great! However, for the previous case you're describing I did not intend for people to try and guess the `src_gid`. Instead it should be pulled directly from the connection they are trying to visualize
```py

conn_idx = 20
gid_idx = 11
src_gid = net_erp.connectivity[conn_idx]['src_range'][gid_idx]
fig, ax = plot_cell_connectivity(net_erp, conn_idx, src_gid)
```

This doesn't get around the difficulty of placing the `src_gid` in a specific location, so I think an interactive plot would be an awesome solution to that.

**Comment by ntolley** [comment]
I don't know if this is just complicating things, but what do you think of a function that returns soma's all gids within a certain radius of an (x,y,z) coordinate? May be a bit too superfluous of a function...

**Comment by rythorpe** [comment]
Apologies if this is stupid question @ntolley , but what does `conn_idx` represent again and how does a user select it?

**Comment by ntolley** [comment]
Definitely not a stupid question, the interface is really awkward to use right now. `conn_idx` is simply the index of a specific connection in `net.connectivity`. There is no way to know _a priori_ the index of the connection you want without simply printing them out (despite me being very proud of the very pretty `__repr__`  I wrote for them 😄)

#367 addresses this directly by allowing users to specify any combination of connection features, and returning a list of indices that match the specified features.

Once I finish up the calcium PR that's the next on my list! It's mostly done but there's some test cleanup that is desperately needed.

**Comment by ntolley** [comment]
Also after the 0.2 release it may be worth thinking of a better data structure for `net.connectivity`. While it's still a bit awkward, we've settled on the current format because it is lightweight (important for pickling/MPI), and still flexible enough to define arbitrarily complex connection patterns.

**Comment by rythorpe** [comment]
> Definitely not a stupid question, the interface is really awkward to use right now. `conn_idx` is simply the index of a specific connection in `net.connectivity`. There is no way to know _a priori_ the index of the connection you want without simply printing them out (despite me being very proud of the very pretty `__repr__` I wrote for them 😄)
> 
> #367 addresses this directly by allowing users to specify any combination of connection features, and returning a list of indices that match the specified features.
> 
> Once I finish up the calcium PR that's the next on my list! It's mostly done but there's some test cleanup that is desperately needed.

I see. I'm assuming there's a reason why `net.connectivity` isn't of type `dict`?

**Comment by ntolley** [comment]
It mainly boils down to it being extremely unintuitive to define the keys for the dict. The key would have to uniquely define all the parameters that make up a connection (loc, receptor, target_type, src_type, etc.) as a first step. So at a minimum your key would need to be a tuple of strings, or some concatenated string of these parameters. And you still run into the same problem addressed by `pick_connectivity`, what if you wanted to pull out all the connections that originate from `L2_basket cells`? That would require a function with an almost identical API.

An argument for using a `dict` is the possibility of redundant connections where it is the same connection class, but the precise `src_gids` and `target_gids` that are connected differ. There's certainly arguments to be made against allowing for redundant connections, and instead the `gids` defining a connection should all be stored in the same entry. But in practice this seems like an overly restrictive requirement, the amount of tests necessary to check for redundant connections would add a lot of complexity for extremely little payoff (all of the models under `network_models` don't have redundancy by default).
