### ISSUE TITLE
Binder link broken

### ISSUE THREAD

**Issue by ntolley** [jonescompneurolab/hnn-core#377]
Can any of you try loading one of the examples on Binder? I am getting this build error:
![image](https://user-images.githubusercontent.com/55253912/123191809-cb2b4100-d46f-11eb-86d2-eb8245b4bf96.png)

**Comment by jasmainak** [comment]
uff ... this is very old

see: https://github.com/jonescompneurolab/hnn-core/blob/master/doc/Dockerfile

we should probably do something like this:

https://github.com/jonescompneurolab/hnn-core/pull/76/files#diff-11e560eb1c0a0b6d8429dfe7434a5b1dcd10b6f2283be4d8ebc59a41fb6c7f33

**Comment by jasmainak** [comment]
do you need it or is it something you just noticed?

**Comment by ntolley** [comment]
Didn't realize this issue has been around. And no I only just noticed when trying to run your interactive plotting PR in binder. Maybe a 0.3 release goal to keep our sanity 😄

**Comment by jasmainak** [comment]
LOL ... I don't know if the interactive plots will work on Jupyter though. Yes, we need to keep sanity :)

**Comment by ntolley** [comment]
Update, still broken but for a different reason:
![image](https://github.com/jonescompneurolab/hnn-core/assets/55253912/db51cffb-f099-4042-b205-edf7271fca6b)
