### ISSUE TITLE
interaction between numspikes, sigma, and sync_within_trials for plot_spikes_hist

### ISSUE THREAD

**Issue by jasmainak** [jonescompneurolab/hnn-core#378]
In @ntolley 's example, I got confused with these different parameters. Should we clarify the docstring? Here is my understanding so far. Please edit!

```sh
numspikes -> number of spikes per target cell
sigma -> standard deviation of spike times (across trials? across cells?)
sync_within_trials -> whether the spikes are synced across trials. If sigma = 0, this has no effect
```

What happens if sigma > 0 but numspikes = 1 and sync_within_trials = True ? Is it equivalent to doing sigma = 0 for a single trial?

**Comment by rythorpe** [comment]
`sigma` -> stdev of the distribution from which spike times are sampled.
- If `sync_within_trials=True`, spike times are sampled independently on each trial **once** for all (artificial) cells.
- If `sync_within_trials=False`, spike times are sampled independently on each trial for each cell.

If `sigma>0`, `numspikes=1`, and `sync_within_trials=True`, a single trial will sample one spike time (that is allowed to deviate from the mean) for all cells; however, If `sigma=0`, only the mean value `mu` can be sampled.

**Comment by jasmainak** [comment]
Do you think there is something to improve in the tutorial documentation or API? Maybe show this [image](
https://user-images.githubusercontent.com/15852194/123784548-8f480f80-d8a5-11eb-9c4a-cf9e1a6590ed.png)
and more explanations for the biological motivations and when each of the parameters should be tweaked? E.g., I am not sure why `numspikes=1` makes sense in the evoked example when it's spikes coming from a population of cells (for `cell_specific=False`). Maybe a viz function to represent the image above? Like [here](https://github.com/jonescompneurolab/hnn/issues/285#issuecomment-814864575) (with suitable tweaks) ...

**Comment by rythorpe** [comment]
> Do you think there is something to improve in the tutorial documentation or API? Maybe show this [image](https://user-images.githubusercontent.com/15852194/123784548-8f480f80-d8a5-11eb-9c4a-cf9e1a6590ed.png)
> and more explanations for the biological motivations and when each of the parameters should be tweaked? E.g., I am not sure why `numspikes=1` makes sense in the evoked example when it's spikes coming from a population of cells (for `cell_specific=False`). Maybe a viz function to represent the image above? Like [here](https://github.com/jonescompneurolab/hnn/issues/285#issuecomment-814864575) (with suitable tweaks) ...

For this specific issue, what about a more verbose docstring? As discussed today for clarifying `numspsikes` and the burst intra-burst-interval between spikes, I definitely think a figure and/or more background info on thalamic drive would be helpful.

**Comment by jasmainak** [comment]
I think that would be sufficient to close this issue! Do you want to give a stab?
