### ISSUE TITLE
inconsistencies in HNN and HNN-core documentation

### ISSUE THREAD

**Issue by jasmainak** [jonescompneurolab/hnn-core#381]
- [ ] Where applicable, the example title should be consistent with tutorial titles on HNN.brown.edu. Note that only examples 1-3 are from the HNN GUI tutorials, 4 and 5 are reproducing results from recent papers. I suggest we have two Tutorial sections one with the title "Tutorials following the detailed HNN GUI tutorials", and "Tutorials reproducing results from recent papers". The suggested subheadings under the first tutorial header are: (1) Simulate Event Related Potentials (ERPs) (2) Simulate Alpha and Beta Rhythms, (3) Simulate Gamma Rhythms. The suggested headings under the second tutorial header are (4) Go from MEG sensor space to HNN interpretation of median nerve evoked response (Thorpe et al 2021) (5) Simulate the influence of beta rhythms on ERPs (Law et al 2021). 
- [x] Under "Tutorials  following the detailed HNN GUI tutorials" ->replace the sentence "These are the detailed tutorials describing..."  with "The following tutorials contain the workflow and code to simulate and visualize commonly studied M/EEG signals including event related potentials and low frequency rhythms in the alpha, beta and gamma bands. The tutorial workflows,  and all parameter values used,  are based on the detailed tutorials provided on the HNN GUI website https://hnn.brown.edu/tutorials, and reproduce a subset of examples and figures in the more elaborated GUI tutorials using the HNN-core API. We strongly recommend that you first go through the background information provided on the HNN website  (https://hnn.brown.edu/overview-uniqueness/) and each of the HNN GUI tutorials, after which the code and instructions in these HNN core tutorials will be clearer. All tutorials build from our prior publications investigating the origin of ERPs and brain rhythms in the somatosensory system, and parameter and data sets are provided to help users get started."
- [x] Within tutorial 01. Simulate Event Related Potentials (ERPs). Replace the first sentence with "This example demonstrates how to simulate a threshold level tactile evoked response, as detailed in the HNN GUI ERP tutorial https://jonescompneurolab.github.io/hnn-tutorials/erp/erp, using HNN-core. We recommend you first review the GUI tutorial. The workflow below recreates an example of the threshold level tactile evoked response, as observed in Jones et al. J. Neuroscience 2007 (e.g. Figure 7 in the GUI tutorial), albeit without a direct comparison to the recorded data". 
- [x] Within tutorial 02. Simulate Alpha and Beta Rhythms.  Replace the first few sentences with  "This example demonstrates how to simulate alpha and beta frequency activity in the alpha/beta complex of the SI mu-rhythm (Jones et al J. Neurophys. 2009), as detailed in the HNN GUI alpha and beta tutorial https://jonescompneurolab.github.io/hnn-tutorials/alpha_and_beta/alpha_and_beta, using HNN-Core. We recommend you first review the GUI tutorial. The workflow below recreates the alpha only rhythm, similar to Figure 5 of the GUI tutorial, and the alpha/beta complex similar to Figure 20 in the GUI tutorial, albeit without visualization of the corresponding time-frequency spectrograms. 
- [x] Within tutorial 0.3 SImuate gamma rhythms. Replace the first sentences with. "This example demonstrates how to simulate gamma rhythms via the well established pyramidal-interneuron-gamma mechanisms (Lee and Jones 2013), as detailed in the HNN GUI gamma tutorial hhttps://jonescompneurolab.github.io/hnn-tutorials/gamma/gamma, using HNN-Core. We recommend you first review the GUI tutorial. The workflow below recreates weak gamma rhythm similar to Figures 4 and 5 of the GUI tutorial, and strong gamma rhythms similar to Figure 12 and 13 in the GUI tutorial. 
- [x] Within tutorial 0.4 Go from MEG sensor space to HNN interpretation of median nerve evoked responses (Thorpe et al 2021).  Update the reference to Ryan's publication once it is on biorxiv (soon...) @rythorpe 
- [x] Within the tutorial 0.5 Simulate the influence of beta rhythms on ERPs (Law et al 2021) , specify at the top that this tutorial changes the local network connectivity structure to be consistent with that in Law et al 2021, and then simulates the results in Figure XX (whatever figure this is in the paper). @ntolley

**Comment by jasmainak** [comment]
@stephanie-r-jones this looks great and actionable. One question I have is: do we want to refer to specific Figure numbers in the HNN-GUI tutorials? This might make maintenance harder for two reasons:

1) If the figure numbers change in the future, we will have to carefully update them in HNN-core as well
2) If there are changes or bug fixes that make the figures not match exactly, it may confuse users. 

I want to avoid the word "reproduce" even though that is the intention because we don't want to be stuck in the loop of trying to match HNN-GUI now that we have validated multiple times that HNN-core works and indeed produces outputs that are exactly the same if we take into account the bugfixes.

**Comment by ntolley** [comment]
Addressed in the last checkbox in:
https://github.com/jonescompneurolab/hnn-core/pull/333/files/1f87ec61a70e6e1def5ad1bc5d1a1e3c5b2ad5b4..631b0a3f66b9129027d56728d7712b24968e5512

**Comment by jasmainak** [comment]
Think @rythorpe your publication is on bioarxiv. Do you want to fix the last remaining checkbox so we can close the issue?

**Comment by rythorpe** [comment]
Done. I think we need to update the first checkbox as well: it's been completed (I'm pretty sure) but the wording is slightly off.
