### ISSUE TITLE
missing docstring in Law2021-model

### ISSUE THREAD

**Issue by cjayb** [jonescompneurolab/hnn-core#384]
https://github.com/jonescompneurolab/hnn-core/blob/d6b08ff60d9a74d517582755d5e0d6d4dbd3df89/hnn_core/network_models.py#L197

Didn't spot this in review :) @ntolley ?

**Comment by ntolley** [comment]
Addressed in #333 (along with many many more fixes)
https://github.com/jasmainak/hnn-core/blob/90f33f3a397005ee300de98909a6e4603e93a22d/hnn_core/network_models.py#L198
