### ISSUE TITLE
show how to compare HNN-core output to data

### ISSUE THREAD

**Issue by jasmainak** [jonescompneurolab/hnn-core#389]
@stephanie-r-jones suggested today that the ERP example should have some comparison with data and perhaps show how the exploration process goes along with computation of RMSE

**Comment by ntolley** [comment]
If we use something other than the GUI tutorial data, it might be good to show how to resample data where the timestamps may be misaligned using `scipy.interpolate.interp1d`, since that will probably come up any time you want to compare data.

**Comment by jasmainak** [comment]
There is an RMSE function in the optimization PR #77 . Maybe worth baking into that ...

**Comment by rythorpe** [comment]
I think we've moved past this with the new GUI + tutorials. Feel free to reopen if anyone disagrees.
