### ISSUE TITLE
deprecate fiddling params

### ISSUE THREAD

**Issue by jasmainak** [jonescompneurolab/hnn-core#402]
Now that #397 is merged, I think we should change the pattern:

```py
params = read_params(params_fname)
net = Network(params)
```

to:

```py
net = read_network_params(fname, add_drives=True)
```

so user doesn't fiddle with `params` dictionary and we encourage using the API. And then remove `add_drives_from_params` is removed from init of `Network`

What do you guys think?

**Comment by rythorpe** [comment]
Sounds like a great idea to me!

**Comment by jasmainak** [comment]
One challenge is how to bake `N_pyr_x` and `N_pyr_y` into the API. Should it be parameters of `Network` and `read_network`? It's something we use in the tests

**Comment by rythorpe** [comment]
I'm not sure I follow. I thought `N_pyr_x` and `N_pyr_y` were parameters defined in the param files?

**Comment by jasmainak** [comment]
see this:

https://github.com/jonescompneurolab/hnn-core/blob/9fd8f5160c89e5f44c1cfc9716fc44a0103a8630/hnn_core/tests/conftest.py#L87-L88
