### ISSUE TITLE
MPI test fails locally

### ISSUE THREAD

**Issue by cjayb** [jonescompneurolab/hnn-core#406]
I've run across this in current `master` when running `test_parallel_backends.py:test_run_mpibackend_oversubscribed`, can any other macOS users confirm?

```bash
E           RuntimeError: MPI simulation failed. Return code: 143

hnn_core/parallel_backends.py:235: RuntimeError
----------------------------- Captured stdout call -----------------------------
MPI will run over 12 processes
Running 2 trials...
numprocs=12
```

This is running on my 4-core Air, so I'd expect `1.5 * 4 == 6` cores, not 12. My environment is:

```
mpi                       1.0                     openmpi    conda-forge
mpi4py                    3.0.3            py38h368b8e5_5    conda-forge
openmpi                   4.1.0                h5807002_1    conda-forge
neuron                    7.8.2                    pypi_0    pypi
```

**Comment by jasmainak** [comment]
I have this issue too. Not sure what's the right fix, we might have dig up the pull request by Blake and see what was the intention. 

Also, are you sure it's [4 logical cores](https://superuser.com/questions/1101311/how-many-cores-does-my-mac-have)?

**Comment by cjayb** [comment]
> Also, are you sure it's [4 logical cores](https://superuser.com/questions/1101311/how-many-cores-does-my-mac-have)?

DUH! No, it's a 1.2 GHz Quad-Core Intel Core i7, so the 12 virtual cores is correct.

**Comment by jasmainak** [comment]
@cjayb I can't seem to reproduce this error any more. Do you still have this issue? I am now installing `mpi4py` on Mac by doing the following:

First install `openmpi-mpicc`:

```sh
$ conda install -c conda-forge openmpi-mpicc
```

Next, do a pip install:

```sh
$ pip install mpi4py
```

The old command:

```py
$ conda install openmpi mpi4py
```

doesn't seem to work for me any more (conda claims it's installed but pip and ipython don't see it)

**Comment by rythorpe** [comment]
I still have this issue on Ubuntu. `openmpi` is installed globally at root but is not installed as a python package.

**Comment by cjayb** [comment]
Still have the problem with mpi and mpi4py from conda-forge... I need to upgrade to Big Sur soon, so will need to create new envs anyway...

**Comment by jasmainak** [comment]
moving to 0.3 ... let's wait for some users to hit this issue
