### ISSUE TITLE
warning for no connections in Network object

### ISSUE THREAD

**Issue by jasmainak** [jonescompneurolab/hnn-core#410]
moving @ntolley 's comment to separate issue:

https://github.com/jonescompneurolab/hnn-core/pull/77#discussion_r683714765

raise a warning of `net.connectivity` has no local connections (but input drives?)

**Comment by jasmainak** [comment]
@ntolley I'm adding it to the 0.2 milestone. I think it would be good to have this warning in so people don't waste many hours debugging

**Comment by ntolley** [comment]
Just added to #416 here: https://github.com/ntolley/hnn-core/blob/cc2fd1c4308e181c99fe9c8bfffb8233d8d70216/hnn_core/dipole.py#L58

Seem good to you?

**Comment by ntolley** [comment]
I can alternatively change it to
```py
if len(net.connectivity) == len(net.external_drives):
```
If we only care about raising an error with a disconnected network. However, there have been situations where that is exactly what someone wanted to simulate.

**Comment by jasmainak** [comment]
> I can alternatively change it to

I'm not sure what that does

It looks good as you have done now

**Comment by ntolley** [comment]
This alternative version would handle the case where there are no connections intrinsic to the network, but the user has added input drives. In any case I am fine with leaving it as is.
