### ISSUE TITLE
Calcium model requires variable conductance for Na and K

### ISSUE THREAD

**Issue by ntolley** [jonescompneurolab/hnn-core#411]
While trying to reproduce the results from Sarah's thesis with `calcium_model` from #333 , I noticed that more channels than just calcium were updated: 
![image](https://user-images.githubusercontent.com/55253912/128954519-22d6d213-2792-4cf3-9dd0-6e98e9600ebb.png)

Considering we did not have access to the thesis while working on this PR it's a pretty understandable mistake. I'll open a PR soon trying to resolve these issues.

**Comment by jasmainak** [comment]
indeed, I seem to have seen this figure. Is the thesis online?

**Comment by stephanie-r-jones** [comment]
Indeed the entire L5 pyramidal neuron biophysics should be swapped out. This is a link to instructions for doing this in HNN-GUI on the website, that links to Carmen's GitHub page where the new L5 parameter neuron and a description of the updates are detailed. https://github.com/kohl-carmen/HNN-AEF. I will email you a copy of Sarah's thesis. Some of her most recent results are not included but she is responsive through email and will meet when necessary.
