### ISSUE TITLE
BUG: Pickling error with simulate_dipole

### ISSUE THREAD

**Issue by ntolley** [jonescompneurolab/hnn-core#432]
@rythorpe discovered running a simulation on joblib, followed by MPI on the same `Network` object throws a picking error due to the nrn objects.

UPDATE: [here's](https://gist.github.com/rythorpe/a963b786c4def555eb0a0a45f18ec089) a demo of the issue

**Comment by jasmainak** [comment]
The hack fix is to add these two lines between the two simulations:

```py

net.cells = dict()
net.n_cells = 0
```

We could put this in `_clear_neuron_objects`. Alternatively, we could just not expose `net.cells` to the user and make it private to be deleted after the simulation finishes. I'm not sure if there is a value in doing that?

**Comment by jasmainak** [comment]
Do you want to give a shot at this @ntolley ?

**Comment by rythorpe** [comment]
> The hack fix is to add these two lines between the two simulations:
> 
> ```python
> net.cells = dict()
> net.n_cells = 0
> ```
> 
> We could put this in `_clear_neuron_objects`.

I like this idea. Why doesn't the `JoblibBackend` trip up as well given that it pickles the `Network` object as well?

> Alternatively, we could just not expose `net.cells` to the user and make it private to be deleted after the simulation finishes. I'm not sure if there is a value in doing that?

If `net.cells` doesn't need to be exposed to the user, why is it an attribute of `Network` to begin with?

**Comment by jasmainak** [comment]
> If net.cells doesn't need to be exposed to the user, why is it an attribute of Network to begin with?

You might be able to answer that: https://github.com/jonescompneurolab/hnn-core/pull/321/files ;-) I thought we should just expose `net.cell_types` but not `net.cells` ...

**Comment by jasmainak** [comment]
> Why doesn't the JoblibBackend trip up as well given that it pickles the Network object as well?

I'm not sure. Maybe JoblibBackend uses a more advanced pickling procedure?

**Comment by rythorpe** [comment]
Turns out `JoblibBackend` also throws a pickling error when `n_jobs` >1. Correspondingly, the only time a parallel backend successfully updates `net.cells` is when `JoblibBackend` bipasses `Joblib.Parallel()` (i.e., when `JoblibBackend(n_jobs=1)` is called directly or when `MPIBackend(n_procs=1)`).

**Comment by rythorpe** [comment]
> > If net.cells doesn't need to be exposed to the user, why is it an attribute of Network to begin with?
> 
> You might be able to answer that: https://github.com/jonescompneurolab/hnn-core/pull/321/files ;-) I thought we should just expose `net.cell_types` but not `net.cells` ...

Hmm, I thought we had all decided once upon a time that it'd be good to expose individual cells to the user. I can't recall the reason though. Maybe @cjayb can shed some light? Was I wrong? If there is not reason to do so, let's remove `Network.cells` altogether and hide the cell instances in `NetworkBuilder`.

Big picture, maybe we can address all three of @ntolley's recent issues with a single PR that removes `Network.cells` and instead updates `Network.cell_types` for plotting.

**Comment by cjayb** [comment]
> Maybe @cjayb can shed some light?

Sorry, I'm drawing a blank. I don't think it's related to the LFP-debacle, if that's where you're going?

**Comment by rythorpe** [comment]
At some point one of us requested that we expose the (Neuron) cell objects to the user in `Network` should an advanced user want to access them. If none us remember the use case for such a scenario, I think that means we can get rid of it.

**Comment by jasmainak** [comment]
It might have been me :) But maybe it causes us more headache than needed. We exposed it in this development cycle, so we can safely remove it without deprecation!
