### ISSUE TITLE
BUG: net.cells empty when simulating with MPIBackend

### ISSUE THREAD

**Issue by ntolley** [jonescompneurolab/hnn-core#434]
JoblibBackend simulations populate `net.cells` with the appropriate `Cell` objects, but it remains empty with MPI

**Comment by jasmainak** [comment]
Indeed, I can reproduce by running [the MPI example](https://jonescompneurolab.github.io/hnn-core/dev/auto_examples/howto/plot_simulate_mpi_backend.html#sphx-glr-auto-examples-howto-plot-simulate-mpi-backend-py). @rythorpe your department?

**Comment by rythorpe** [comment]
`JoblibBackend` only works when `n_jobs=1`. See https://github.com/jonescompneurolab/hnn-core/issues/432#issuecomment-917793205.
