### ISSUE TITLE
plot_dipole should iterate over layers

### ISSUE THREAD

**Issue by jasmainak** [jonescompneurolab/hnn-core#445]
Currently, `plot_dipole` only accepts a `layer` to be a string. It should be possible to accept it as a list and then make different subplots for each layer if a list is provided. In that case, `axes` provided should also be a list

https://github.com/jonescompneurolab/hnn-core/blob/0406ed1a2b2335b786e83eb1698f27a5c3dcdadc/hnn_core/viz.py#L226-L228

This way user doesn't have to do a for loop for plotting the different layers

**Comment by chenghuzi** [comment]
Will work on this now

**Comment by jasmainak** [comment]
go go go @chenghuzi !
