### ISSUE TITLE
BUG: Evoked drive with connection probability <1.0 breaks simulation

### ISSUE THREAD

**Issue by ntolley** [jonescompneurolab/hnn-core#455]
As the title indicates, this is devilishly simple to reproduce and this behavior does not happen for the bursty drives. Additionally it is not related to the choice in model.

```py
from hnn_core import jones_2009_model, simulate_dipole
net = jones_2009_model()

weights_ampa_d1 = {'L2_basket': 0.006, 'L2_pyramidal': 0.000074, 'L5_pyramidal': 0.5, 'L5_basket': 0}
synaptic_delays_d1 = {'L2_basket': 0.1, 'L2_pyramidal': 0.1, 'L5_pyramidal': 0.1, 'L5_basket': 0}

net.add_evoked_drive(
    'evdist1', mu=60.815475, sigma=8.695293, numspikes=1, weights_ampa=weights_ampa_d1,
    weights_nmda=None, location='proximal',
    synaptic_delays=synaptic_delays_d1, probability=0.5, event_seed=4)

simulate_dipole(net, tstop=100)
```
![image](https://user-images.githubusercontent.com/55253912/149266805-5cf7f77c-484b-4d70-a830-8572c17dbd0f.png)

Looking at the tests, the reason this isn't caught is because they never actually run `simulate_dipole()`. This bug is definitely in my wheelhouse so I'll report back with a PR once I do more digging. Of course feel free to take a look yourself! Words of encouragement will suffice as well ;)

**Comment by jasmainak** [comment]
You have my blessing to fix this :)
