### ISSUE TITLE
BUG: add_poisson_drive doesn't accept floats for rate_constant

### ISSUE THREAD

**Issue by ntolley** [jonescompneurolab/hnn-core#457]
Found while working on #455. `net.add_poisson_drive()` expects a dictionary for the `rate_constant` argument. The following script fails:
```py
from hnn_core import simulate_dipole, jones_2009_model
net = jones_2009_model()
weights_ampa = {'L2_pyramidal': 0.0008, 'L5_pyramidal': 0.0075}
synaptic_delays = {'L2_pyramidal': 0.1, 'L5_pyramidal': 1.0}

n_drive_cells = 'n_cells'  # default for poisson drive
cell_specific = True
net.add_poisson_drive(
    'poisson', rate_constant=1.0, weights_ampa=weights_ampa,
    location='proximal', synaptic_delays=synaptic_delays,
    cell_specific=cell_specific)

simulate_dipole(net, tstop=1)
```
![image](https://user-images.githubusercontent.com/55253912/149767971-fa49d885-55ce-4df4-a5f4-5e88370a0534.png)
The documentation indicates that this should accept a float or a dictionary so this should be resolved quickly.

I found this because I am adding a `simulate_dipole()` call to `test_drives.py`. @jasmainak I can probably handle this in the same PR, but they are two unrelated issues.

**Comment by ntolley** [comment]
As a general comment too I'm noticing there are hardly any explicit type checks in the drives API, maybe that constitutes a good first issue? It really just amount to using the type check functions used elsewhere, and writing test cases that loop over the arguments.

**Comment by jasmainak** [comment]
agree that it's a good first issue!
