### ISSUE TITLE
remove redundant function drive_event_times

### ISSUE THREAD

**Issue by jasmainak** [jonescompneurolab/hnn-core#463]
It looks we have two copies of the same function:

drive_event_times
_drive_cell_event_times

we should remove one of them and update the tests to use only one function

**Comment by rythorpe** [comment]
This is addressed in #431. I'll need to update myself on the status of that PR but I think it can be pushed through rather quickly.

**Comment by jasmainak** [comment]
indeed, sorry about missing that!

**Comment by raj1701** [comment]
Hey @jasmainak @rythorpe can I work on this?

**Comment by rythorpe** [comment]
Turns out this is actually already being addressed in #431. Sorry @raj1701!

**Comment by raj1701** [comment]
No problem at all @rythorpe. I will work on something else
