### ISSUE TITLE
Saving param file with hnn_core

### ISSUE THREAD

**Issue by carolinafernandezp** [jonescompneurolab/hnn-core#468]
Hi,
I'm using hnn_core to run simulations. I set up the parameters as it is done here: 

https://jonescompneurolab.github.io/hnn-core/stable/auto_examples/workflows/plot_simulate_evoked.html#sphx-glr-auto-examples-workflows-plot-simulate-evoked-py

Now I want to save the corresponding param file so that I can call it with hnn_core.read_params() as it is done here: 

https://jonescompneurolab.github.io/hnn-core/stable/auto_examples/howto/plot_optimize_evoked.html#sphx-glr-auto-examples-howto-plot-optimize-evoked-py

How can I save the param file as a .json or .param?

Thanks

**Comment by carolinafernandezp** [comment]
Thanks for your response.

I found a set of parameters that simulates my data and now I want to optimize them. Which is why I'm trying to save the param file by calling:

`optimize_evoked()`

because `optimize_evoked()` takes in the .json param file

**Comment by jasmainak** [comment]
ahhhh ... not any more! Thanks to fantastic work by @rythorpe you can now provide a `net` object. See:

https://jonescompneurolab.github.io/hnn-core/dev/auto_examples/howto/optimize_evoked.html#sphx-glr-auto-examples-howto-optimize-evoked-py

But you'll need the latest development version for this. You can do:

```sh
$ pip install --upgrade https://api.github.com/repos/jonescompneurolab/hnn-core/zipball/master
```

**Comment by carolinafernandezp** [comment]
I have an additional question along the same lines, is it possible to run optimization with `optimize_evoked` while keeping some parameters "fixed" and optimizing only the rest?

**Comment by rythorpe** [comment]
Not currently, although the codebase is setup to accomodate a feature like that in the near future. Which parameters are you wanting to fix and which ones are you wanting to vary?

**Comment by carolinafernandezp** [comment]
So my simulation consists of 3 evoked inputs (one proximal and 2 distal), and I'd like to optimize only the second distal input while keeping the others fixed.

**Comment by rythorpe** [comment]
> So my simulation consists of 3 evoked inputs (one proximal and 2 distal), and I'd like to optimize only the second distal input while keeping the others fixed.

Okay yeah, that would be a super straightforward enhancement feature to the `optimize_evoked` function - only a few lines of code. If you're inspired, feel free to give it a shot; otherwise, I'll try to give you a heads up once this feature is added!

**Comment by carolinafernandezp** [comment]
I'll give it a shot! Thanks

**Comment by jasmainak** [comment]
could we open an issue about this? What would the API look like?
