### ISSUE TITLE
Plot raster for individual trials

### ISSUE THREAD

**Issue by wagdy88** [jonescompneurolab/hnn-core#471]
Hi, 
My name is Mohamed ElSayed, and I am a psychiatrist at DMHC working with Dr. Mohamed Sherif on mismatch negativity. We have been trying to plot raster for individual trials, yet we were unable to access net.cell_response for individual trials. Would appreciate your help. 
Thanks

**Comment by jasmainak** [comment]
I don't think it's supported at the moment but it should be straightforward to implement. Possibly a `trial_idx` argument to `plot_spikes_raster`. @ntolley would you have time for this?

**Comment by ntolley** [comment]
Yeah this was a bit of an oversight since most of our tests with hnn-core only run 1 trial. I'll take a look!

**Comment by rythorpe** [comment]
I think the right way to do this would be to run separate single-trial simulations with different seed values and retrieve the different `net.cell_response` objects that way. I only suggest this because the intuition behind a simulation with multiple trials is to capture intrinsic stochasticity in the network that can be averaged out to generate mean statistics. This allows us to simulate signals that better match experimental measurements, not to provide a mechanism for running individual trials that can be analyzed separately from the other trials of a simulation.

**Comment by rythorpe** [comment]
> @rythorpe if you had this wisdom 30 minutes ago when I started coding smile
> 
> I suppose where this becomes a bit cumbersome is in the `plot_spikes_hist` like in #452 [here](https://github.com/jonescompneurolab/hnn-core/issues/454#issuecomment-1023742097) where inspecting individual trials can be informative to see how much variance is due to seeding alone.

Oh no, sorry for the delay! For that use-case, the user will still need to call `plot_spikes_hist` in a loop even with the ability to index `cell_response` by trial, right?

**Comment by ntolley** [comment]
That's definitely one option. I think the usefulness comes from inspecting the exact influence of drive spike times on the dipole and cell spiking. @jasmainak any thoughts?

In any case @wagdy88 the short term solution as suggested by @rythorpe is to instantiate multiple `Network` objects like:
```py
net1 = jones_2009_model()
net2 = net1.copy()
```
And make separate plots. Alternatively you can manually inspect the data for each trial in the attributes:
```py
net.cell_response.spike_times[trial_idx]
net.cell_response.spike_types[trial_idx]
net.cell_response.spike_gids[trial_idx]
```

**Comment by wagdy88** [comment]
This is very helpful, thanks @jasmainak,  @ntolley , and @rythorpe. I am not very familiar with trial_idx, could you explain it more?

**Comment by jasmainak** [comment]
I think whatever you do should be consistent between different objects:

```py
dpl[trial_idx].plot()
net.cell_response[trial_idx].plot_xxx()
net.rec_arrays['shank1'][trial_idx].plot()
```

seems the most consistent to me. Is the indexing of `cell_response` by gid actually used ?

**Comment by jasmainak** [comment]
`trial_idx` stands for "trial index". It's the index of the trial you want to make a plot for

**Comment by wagdy88** [comment]
I think we tried the net.cell_response[trial_idx] but didn't lead us anywhere - I might be mistaken though-. Will try it again. Thanks!

**Comment by jasmainak** [comment]
Sorry I meant that it needs to be implemented in a consistent way ... not that it has already been implemented :)

**Comment by wagdy88** [comment]
Oh I see, thanks for explaining :)
So, for now, I need to create multiple net objects (one for each trial) to be able to get multiple rasters, right? 
If yes, then another question, will I get the same trial if I don't change the seed?

**Comment by mkhalil8** [comment]
@wagdy88 Mohamed the cell_response of each net object will contain all the raster plots for the trials you ran on that network.
You can save it using:
``` python
net.cell_response.write('trial'+'spk_%d.txt')
```
which will save all the rasters for each trial.

You can then read them back using:
```python
from hnn_core import read_spikes
spk_trial1= read_spikes('controlspk0.txt')
spk_trial1.plot_spikes_raster()

```

**Comment by wagdy88** [comment]
Thanks @mkhalil8 , will try that and see if it works

**Comment by mkhalil8** [comment]
> That's definitely one option. I think the usefulness comes from inspecting the exact influence of drive spike times on the dipole and cell spiking. But I can see how putting too much emphasis on single trials is quite misleading
> 
> @jasmainak any thoughts?
> 
> In any case @wagdy88 as suggested the short term solution as suggested is to instantiate multiple `Network` objects like:
> 
> ```python
> net1 = jones_2009_model()
> net2 = net1.copy()
> ```
> 
> And make separate plots after adding drives to both networks separately. Alternatively you can manually inspect the data for each trial in the attributes:
> 
> ```python
> net.cell_response.spike_times[trial_idx]
> net.cell_response.spike_types[trial_idx]
> net.cell_response.spike_gids[trial_idx]
> ```

I have compared the trials on each network using this method and found the dipoles exactly the same. For example trial 0 on net1 is exactly trial0 on net2. So the seed order should be the same and you can compare their respective rasters.

**Comment by rythorpe** [comment]
> I think whatever you do should be consistent between different objects:
> 
> ```python
> dpl[trial_idx].plot()
> net.cell_response[trial_idx].plot_xxx()
> net.rec_arrays['shank1'][trial_idx].plot()
> ```
> 
> seems the most consistent to me. Is the indexing of `cell_response` by gid actually used ?

@jasmainak I though what we decided back when we created the `CellResponse` object was that it was specifically a place for storing attributes of individual cells and would thus be indexed at the highest level according to GID (contrary to the `Dipole` object which is an output, or "response attribute", of the entire network. Correspondingly, attributes of individual cells (e.g., `net.cell_response[gid].spike_times`), can store information that is trial dependent and indexed by trial.

**Comment by rythorpe** [comment]
> Oh I see, thanks for explaining :) So, for now, I need to create multiple net objects (one for each trial) to be able to get multiple rasters, right? If yes, then another question, will I get the same trial if I don't change the seed?

Correct, the purpose of allowing the user to set the seed in e.g. `net.add_evoked_drive()` is to ensure exact reproducibility when a given `Network` object is simulated under the same seed conditions. Alternatively, if you wish to explore variance between simulations, one might wish to modulate the seed and observe how the `Network` object responds to the same fundamental drives and simulation conditions.

**Comment by jasmainak** [comment]
thanks @mkhalil8 for pitching in. That's definitely one way to do it but hardly ideal. I'd love to have a one liner that does it and doesn't require writing a file to disk. I can also live with 

```py
net.cell_response.plot_spikes_raster(trial_idx=None)
```

while we don't want to over-emphasize single trials, users also should have the tools at hand to inspect the simulation results with the granularity they like. And this seems simple enough to implement on our end.

**Comment by wagdy88** [comment]
Thanks @jasmainak.
I totally agree, a one liner would be great. 
The thing is for mismatch negativity, it would very helpful to compare the rasters from one trial to the next.
