### ISSUE TITLE
plot_dipole for multiple trials

### ISSUE THREAD

**Issue by jasmainak** [jonescompneurolab/hnn-core#473]
Currently, `plot_dipole` shows this for multiple trials:

![image](https://user-images.githubusercontent.com/15852194/158681137-103fc56d-da5a-4c72-b1fb-390ae29eee40.png)

I think what we want is something like this:

![image](https://user-images.githubusercontent.com/15852194/158681218-7690c98b-9c20-4079-9544-b0948953521c.png)

so the average dipole is overlaid on trial-level dipoles and the trial-level dipoles are in a single color.

**Comment by chenghuzi** [comment]
OK I'll work on this first

**Comment by jasmainak** [comment]
great!

**Comment by jasmainak** [comment]
closed by #476
