### ISSUE TITLE
Matplotlib warning in plot_spikes_hist with multiple trials

### ISSUE THREAD

**Issue by chenghuzi** [jonescompneurolab/hnn-core#486]
With the following code:
```
#...
hnn_core_root = op.join(op.dirname(hnn_core.__file__))
params_fname = op.join(hnn_core_root, 'param', 'default.json')
params = read_params(params_fname)

# net = jones_2009_model()
net = Network(params, add_drives_from_params=True)

with MPIBackend():
    dpls = simulate_dipole(net, tstop=170., n_trials=3)

window_len, scaling_factor = 30, 3000
for dpl in dpls:
    dpl.smooth(window_len).scale(scaling_factor)

fig, axes = plt.subplots(2,
                         1,
                         sharex=True,
                         figsize=(6, 6),
                         constrained_layout=True)
plot_dipole(dpls, ax=axes[0], layer='agg', average=True)
net.cell_response.plot_spikes_hist(ax=axes[1])
#...
```

we got some warnings

![image](https://user-images.githubusercontent.com/11160442/176988314-71760eab-dab1-40f3-93f8-bdcbefeed237.png)

We also got similar warnings for spike plots

**Comment by jasmainak** [comment]
Thanks for reporting this. Would you mind editing the code above so I can copy paste to reproduce? Let me know when this is done.

**Comment by chenghuzi** [comment]
```Python
import os.path as op

import hnn_core
import matplotlib.pyplot as plt
from hnn_core import (JoblibBackend, MPIBackend, jones_2009_model,
                      simulate_dipole, read_params, Network)
from hnn_core.viz import plot_dipole

hnn_core_root = op.join(op.dirname(hnn_core.__file__))
params_fname = op.join(hnn_core_root, 'param', 'default.json')
params = read_params(params_fname)

# net = jones_2009_model()
net = Network(params, add_drives_from_params=True)

# with JoblibBackend(n_jobs=2):
with MPIBackend():
    dpls = simulate_dipole(net, tstop=170., n_trials=3)

window_len, scaling_factor = 30, 3000
for dpl in dpls:
    dpl.smooth(window_len).scale(scaling_factor)

fig, axes = plt.subplots(2,
                         1,
                         sharex=True,
                         figsize=(6, 6),
                         constrained_layout=True)
plot_dipole(dpls, ax=axes[0], layer='agg', average=True)
net.cell_response.plot_spikes_hist(ax=axes[1])

plt.savefig("erp_sample.png")

```
generates
![image](https://user-images.githubusercontent.com/11160442/177192038-47ca1e78-5df3-439a-8df7-ae44fd402f66.png)

**Comment by rythorpe** [comment]
At first glance, I'm guessing this error occurs when certain cells spike while others don't?

**Comment by jasmainak** [comment]
I can't reproduce ... what version of matplotlib are you using?

**Comment by rythorpe** [comment]
I was able to reproduce this error. The problem is due to the code in [this](https://github.com/jonescompneurolab/hnn-core/blob/9850f20a65c1e892a660f52b63aa861de3c2f429/hnn_core/viz.py#L351) 'if' statement and can easily be solved by either setting the `dtype` argument when instantiating the `np.array` or by actually looping over the indices in `trial_idx` (which is actually a `list` of `int` here) and appending selected trials to a master array of spikes. The latter solution would be preferable as it'd be much easier to intuitively read.
