### ISSUE TITLE
plot_dipole function does not check instance type

### ISSUE THREAD

**Issue by jasmainak** [jonescompneurolab/hnn-core#511]
The [plot_dipole](https://jonescompneurolab.github.io/hnn-core/stable/generated/hnn_core.viz.plot_dipole.html#hnn_core.viz.plot_dipole) function does not check the type of object. This leads to errors such as [reported here](https://github.com/jonescompneurolab/hnn-core/discussions/505#discussioncomment-3171051) by @wagdy88

Easy fix for a new contributor

**Comment by raj1701** [comment]
Hey @jasmainak can you please check the PR...
