### ISSUE TITLE
GUI should scale in docs

### ISSUE THREAD

**Issue by jasmainak** [jonescompneurolab/hnn-core#527]
Currently the GUI doesn't scale properly in the docs:

![image](https://user-images.githubusercontent.com/15852194/182054110-302d016c-cec5-4028-bab3-7213657fea6a.png)

either it should be scaled or should occupy a wider area of the screen ... so users don't have to scroll to see the full GUI

**Comment by jasmainak** [comment]
I'm labeling issues @chenghuzi for the GUI so you can get to them when you are bored with writing the tutorial

**Comment by chenghuzi** [comment]
This is due to the constraint in the notebook level. Not sure if we can bypass this but I'll try

**Comment by jasmainak** [comment]
If you can scale it according to the space available (instead of hardcoding pixel size), would it work? You can even have a visualization layout option that has only one plot ... and it can be the default
