### ISSUE TITLE
set DYLD_LIBRARY_PATH for macOS in parallel.rst

### ISSUE THREAD

**Issue by rythorpe** [jonescompneurolab/hnn-core#531]
We should be setting the `DYLD_FALLBACK_LIBRARY_PATH` environment variable, not `LD_LIBARY_PATH`, after installing the dependencies for `MPIBackend` to point NEURON to the appropriate MPI libraries. See [here](https://stackoverflow.com/questions/3146274/is-it-ok-to-use-dyld-library-path-on-mac-os-x-and-whats-the-dynamic-library-s) for more details.

**Comment by jasmainak** [comment]
no opinion ...

feel free to open a PR!
