### ISSUE TITLE
GUI tests failing

### ISSUE THREAD

**Issue by ntolley** [jonescompneurolab/hnn-core#552]
Hate to be the bearer of bad news but @rythorpe and I have noticed that the master branch is failing. It seems to be restricted to `test_gui.py`
![image](https://user-images.githubusercontent.com/55253912/185972137-fb9442d3-bd65-4b0b-9322-34843e9fe32e.png)

@chenghuzi @jasmainak do you know what the index error is referring to?

**Comment by ntolley** [comment]
Also the tests were passing on previous commits with the same `test_gui.py` so this seems to have popped up spontaneously.

**Comment by jasmainak** [comment]
I have no clue honestly ...

**Comment by chenghuzi** [comment]
This is weird, as I just synced to the latest master and tried on my local machine:
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/11160442/186409619-449a05d4-72ea-4113-8ced-7dbc7a425fcf.png">

It seems there's no errors.

**Comment by jasmainak** [comment]
Did you see the detailed error trace? I see:

![image](https://user-images.githubusercontent.com/15852194/186489350-7d0ccc3a-13dd-4035-ac9e-5e94bf1fb9e5.png)

**Comment by jasmainak** [comment]
A new release of ipywidgets was made on Aug 18, could that explain the problem?

**Comment by ntolley** [comment]
Can confirm, just ran `pip install --upgrade ipywidgets` and it broke the previously working tests

**Comment by jasmainak** [comment]
maybe we could have a matrix here for the ipywidgets: https://github.com/jonescompneurolab/hnn-core/blob/df833b4d318ea1397cc09cfe0474a890a4a6239d/.github/workflows/unit_tests.yml#L15-L16

Since the ipywidgets API appears to be still evolving. Ideally the GUI should work for last 2 years of release of ipywidgets ...

**Comment by ntolley** [comment]
Up to you, I'm pretty sure I've figured out the issue and have the tests passing. It is just an API change unfortunately.

**Comment by ntolley** [comment]
@jasmainak should I open a separate PR to resolve the error and do a rapid merge?

**Comment by jasmainak** [comment]
go for it!
