### ISSUE TITLE
Same param. No reloading.To force reloading, hit "clear uploaded parameters" button

### ISSUE THREAD

**Issue by jasmainak** [jonescompneurolab/hnn-core#558]
Whenever I try to load parameters from a file, I get the above message. I am not sure what it means. It's a it unclear to me since I thought loading parameters should clear the existing parameters anyway? cc @chenghuzi

**Comment by jasmainak** [comment]
Something is buggy here ... I am seeing more drives than expected. Somehow old parameters are not being erased.

**Comment by chenghuzi** [comment]
should be fixed in 3af4779aa91bb9e9d7985a4565a3c13daf28415b

**Comment by jasmainak** [comment]
make sure to mark this issue in the PR description so that it closes when the PR is merged
