### ISSUE TITLE
CircleCI jobs speedup

### ISSUE THREAD

**Issue by chenghuzi** [jonescompneurolab/hnn-core#561]
Now it takes about 25 mins to build our doc and most of the time is spent on the doc building step.
<img width="1361" alt="image" src="https://user-images.githubusercontent.com/11160442/187120459-27a333fb-2a37-42ce-b77d-126a772dd3c6.png">

And a large part of dock building is about running examples. Could we use some caching mechanism to avoid running them repeatedly if the corresponding code is not changed?

**Comment by chenghuzi** [comment]
> yeah that's something we could certainly consider ... caching can make debugging harder though. Are you still running the notebook twice? I think you mentioned that nbconvert doesn't use "run all", so you could use nbconvert once and avoid running the tutorial twice?

No it's not running twice anymore. And even with double running, the time is mainly spent on previous examples as I noticed that some simulations run >=300ms so they're really slow

**Comment by jasmainak** [comment]
@chenghuzi take a look here: https://github.com/mne-tools/mne-python/blob/main/.circleci/config.yml

I think `$ make html` with sphinx-gallery should only rebuild the examples that have changed if you cache them

**Comment by rythorpe** [comment]
I was about to close this issue, however, we seem to be having a problem getting CircleCI to pass on master. Any thoughts @chenghuzi?

**Comment by chenghuzi** [comment]
yes I think we can safely close this now. For the CI problem, which one are you referring to? the MPI one?

**Comment by rythorpe** [comment]
No, it has something to do with the document build process for the GUI timing out. See [here](https://app.circleci.com/pipelines/github/jonescompneurolab/hnn-core/2361/workflows/3caa1e76-a782-422c-b124-c147443bfd56/jobs/2602).

**Comment by chenghuzi** [comment]
> No, it has something to do with the document build process for the GUI timing out. See [here](https://app.circleci.com/pipelines/github/jonescompneurolab/hnn-core/2361/workflows/3caa1e76-a782-422c-b124-c147443bfd56/jobs/2602).

I fetched the corresponding PR and it works locally. I suspect it's the cache that failed the building process. I'll dig further to see if it's really the issue.

**Comment by chenghuzi** [comment]
Wait I got it succeed [here](https://app.circleci.com/pipelines/github/chenghuzi/hnn-core/260/workflows/bc0d2f18-f13f-47b2-b9c3-e6370090a92a/jobs/292). This might due to the different namespace for the same cached content. I'll re-run to see if it works

**Comment by jasmainak** [comment]
Are you sure it's a cache issue? I suspect it succeeds stochastically depending on the CI load. You might need to make the example more verbose to stop that error for good.

**Comment by chenghuzi** [comment]
> Are you sure it's a cache issue? I suspect it succeeds stochastically depending on the CI load. You might need to make the example more verbose to stop that error for good.

I'm not sure as both my local build and a new build in my repo on CircleCI worked. On the other hand, I tried to re-run your build and it failed again, which made me to guess it might be the cache key. You can check if it's the case simply by changing the content in `.circleci/build_cache`.
