### ISSUE TITLE
GUI example building should respect make commands

### ISSUE THREAD

**Issue by jasmainak** [jonescompneurolab/hnn-core#601]
The expected behavior of :

```sh
$ make html-noplot
```

is to only convert the rsts to html without execting any examples. While the expected behavior of:

```sh
$ make html
```

is to execute the examples to generate new rsts and convert them to html.

However, the GUI examples currently execute even if one does `make html-noplot`. This is non-ideal for developers looking to quickly test if the output looks as expected.

Any easy fix possible @chenghuzi  ?

**Comment by chenghuzi** [comment]
> 
`nbconvert` has something like an execution flag in their command-line tool. So there should be a way to do so, if we can dynamically adjust this option according to the make option.
