### ISSUE TITLE
Loading data in the new GUI

### ISSUE THREAD

**Issue by chenghuzi** [jonescompneurolab/hnn-core#607]
Currently, we can only create and compare new simulations in the new web-based GUI. However, it would be worthwhile to allow users to upload existing simulations, possibly from previous experiments with hnn-core without GUI, as well as real data (dipoles). This would also serve as a basis for a possible future optimization functionality.

**Comment by jasmainak** [comment]
@chenghuzi I think as a first step, you should allow users to upload real data ... uploading previous simulations is more complicated

**Comment by jasmainak** [comment]
@chenghuzi I think this would be really helpful to have for the 0.3 release ... just for real data, not for previous simulations. Any chance you can get to it in the coming days?

**Comment by chenghuzi** [comment]
Sure! Let me create a PR first, and then we can discuss it in tomorrow's meeting

**Comment by chenghuzi** [comment]
Also see #618
