### ISSUE TITLE
Incorrect plot drawn in plot_simulate_alpha.py example workflow

### ISSUE THREAD

**Issue by dylansdaniels** [jonescompneurolab/hnn-core#633]
Also, all of the workflows run, but the plot wasn't showing correctly in the final example of the alpha workflow where you have the 3 subplots. It was drawing the first plot from plot_spikes_hist and not drawing the final fig after adding the dipole and psd subplots. 

It displays properly when adding the show=False arg to plot_spikes_hist. Just wanted to flag that

_Originally posted by @dylansdaniels in https://github.com/jonescompneurolab/hnn-core/discussions/629#discussioncomment-5483340_

**Comment by jasmainak** [comment]
Yes, this needs to be fixed!

**Comment by ntolley** [comment]
I think this issue has been fixed:

![image](https://github.com/jonescompneurolab/hnn-core/assets/55253912/283d94de-8958-4805-90b4-89fcc43113dc)
