### ISSUE TITLE
test_mpi_failure periodically fails on CI servers

### ISSUE THREAD

**Issue by rythorpe** [jonescompneurolab/hnn-core#634]
I suspect that the issue here might be caused by variance in the number of cores in the CI allocation and/or how the `OMPI_MCA_btl = 'self'` environmental variable is handled such that OpenMPI successfully (or unsuccessfully) fails.

**Comment by ntolley** [comment]
This honestly hasn't been a problem as of late, the tests pass very reliably so I'm going to close
