### ISSUE TITLE
cell response raster plots should show all neurons in the network model

### ISSUE THREAD

**Issue by jasmainak** [jonescompneurolab/hnn-core#658]
As discussed in the group meeting, we should show all neurons, not just the neurons that spike.

**Comment by jasmainak** [comment]
Also we should use: https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.eventplot.html instead of `scatter` as mentioned by @ntolley

**Comment by samadpls** [comment]
Can I take this issue, and Could you provide me with more context regarding this issue?

**Comment by jasmainak** [comment]
it's related to this function: https://jonescompneurolab.github.io/hnn-core/stable/generated/hnn_core.CellResponse.html#hnn_core.CellResponse.plot_spikes_raster

when some cells do not spike, this plot omits those cell types. We want to always plot every cell type.
