### ISSUE TITLE
simplify cell morphology with updated segment coordinates

### ISSUE THREAD

**Issue by rythorpe** [jonescompneurolab/hnn-core#659]
As discussed in https://github.com/jonescompneurolab/hnn-core/pull/651#discussion_r1242400936, we should consider simplifying the codepath for how cell segment coordinates are assigned/determined. Currently, we create a segment with coordinates, build the cell in NEURON, modify its length/radius using the NEURON API, then retrieve the updated coordinates from the NEURON instantiation. We should consider updating the original segment coordinates so that we don't need to build the cell in NEURON in order to determine it's final morphology.

**Comment by ntolley** [comment]
This should be closed by #651 when it is merged

**Comment by rythorpe** [comment]
If I recall @ntolley, we resolved this by adding a function that resets cell section attributes before the model is sent to NEURON. Is that correct?

**Comment by ntolley** [comment]
Yup! @raj1701 implemented this last year by doing the noble work of rewriting the original C++ code :sunglasses:
