### ISSUE TITLE
[JOSS] Documentation

### ISSUE THREAD

**Issue by isdanni** [jonescompneurolab/hnn-core#676]
Linking https://github.com/openjournals/joss-reviews/issues/5848 to track review progress.

Just one very minor change:

>  A statement of need: Do the authors clearly state what problems the software is designed to solve and who the target audience is?

Maybe add a few sentences to https://jonescompneurolab.github.io/hnn-core/stable/index.html after "This is a leaner and cleaner version of the code based off the [HNN repository](https://github.com/jonescompneurolab/hnn)."?  Something like the **About** section in the [GitHub page](https://github.com/jonescompneurolab/hnn-core). Direct copy and paste works too.

**Comment by rythorpe** [comment]
Thanks for the feedback @isdanni! We've implemented your suggestion, but feel free to reopen this issue if you feel we didn't address it adequately.
