### ISSUE TITLE
tests: add axis data checks for all plots available in GUI

### ISSUE THREAD

**Issue by gtdang** [jonescompneurolab/hnn-core#697]
Add checks to `test_gui.py` to make sure all GUI plots actually plot data on the axis.  See #695 for the added checks on the default plots. Currently there are no checks (aside from the default plots) to make sure plots are not empty. Empty plots can occur when an error occurs between clicking the plot/run button and the GUI calling the plot function from the viz module.  

The default figures are the figures that are automatically generated after running a simulation. The figures that need to be checked are the figures that the user can manually create using the Visualization tab. See image below. 
![Screenshot 2024-03-12 at 10 33 34 AM](https://github.com/jonescompneurolab/hnn-core/assets/53052793/397fb497-cc45-47a6-b10c-20c39a47cce5)

Of this list "current dipole" and "histogram" don't need checks as they are part of the default set of plots. The others will need to have unique test functions developed except for the spectrogram, which already has a unique test `test_gui_adaptive_spectrogram`. However the spectrogram does need to have a check for if data is plotted.

**Comment by jasmainak** [comment]
Absolutely ... PR is welcome!

**Comment by samadpls** [comment]
@jasmainak, can I take this issue? 😋
