### ISSUE TITLE
GUI cell parameters

### ISSUE THREAD

**Issue by gtdang** [jonescompneurolab/hnn-core#712]
Ability to set additional cell parameters such synapse, biophysics, and geometry.

The old GUI had the ability to set more cell parameters. The Gamma tutorial includes changing L5 pyr synapse GABAA decay time. There are many more synapse parameters as well as biophysics and geometry tabs accessible. [IMAGE](https://raw.githubusercontent.com/jonescompneurolab/hnn-tutorials/master/gamma/images/image42.png)

**Comment by jasmainak** [comment]
This is done by:

```py
net_jones = jones_2009_model()

jones_rise = net_jones.cell_types['L5_pyramidal'].synapses['gabab']['tau1']
law_rise = net.cell_types['L5_pyramidal'].synapses['gabab']['tau1']
print(f'GABAb Rise (ms): {jones_rise} -> {law_rise}')

jones_fall = net_jones.cell_types['L5_pyramidal'].synapses['gabab']['tau2']
law_fall = net.cell_types['L5_pyramidal'].synapses['gabab']['tau2']
print(f'GABAb Fall (ms): {jones_fall} -> {law_fall}\n')
```

as documented in this example:

https://jonescompneurolab.github.io/hnn-core/stable/auto_examples/workflows/plot_simulate_beta.html#sphx-glr-auto-examples-workflows-plot-simulate-beta-py

**Comment by kmilo9999** [comment]
@ntolley @gtdang 
I'm having difficulties finding the `Dendrite capacitive density` and `Dendrite resistivity` parameters inside the cell types L2 and L5 pyramidal structures.
I do see:
```
Apical Dendrite Trunk length
Apical Dendrite 1 length
Apical Dendrite 1 diameter
Apical Dendrite Tuft length
Apical Dendrite Tuft diameter
Oblique Apical Dendrite length
Oblique Apical Dendrite diameter
Basal Dendrite 1 length
Basal Dendrite 1 diameter
Basal Dendrite 2 length
Basal Dendrite 2 diameter
Basal Dendrite 3 length
Basal Dendrite 3 diameter
```
But not the ones I mentioned.
Can you point me to them in the `hnn_core/cells_default.py` code?

**Comment by ntolley** [comment]
Hey @kmilo9999 you can access them from the code like this:

```py
from hnn_core import jones_2009_model
net = jones_2009_model()
section = net.cell_types['L5_pyramidal'].sections['soma']
print(section.Ra) # resistance
print(section.cm) # capacitance
```
```
200.0
0.85
```

Is that everything you need? I can point you to the lines where this shows up in `cells_default.py` if you still need
