### ISSUE TITLE
GUI tonic inputs

### ISSUE THREAD

**Issue by gtdang** [jonescompneurolab/hnn-core#715]
Ability to set tonic bias parameters 

Add a way to interface with .add_tonic_bias method to set Amplitude, start time, and end time for each layer and cell type.

- [x] Disable location radio buttons when the Tonic radio is selected
- [x] Add tonic accordion with t0 and tstop and cell amplitudes
- [x] Information from widgets should populate Network on simulation run

**Comment by jasmainak** [comment]
@gtdang just wanted to flag that there is already an open PR: https://github.com/jonescompneurolab/hnn-core/pull/635 with discussion. Would be great to take over from there or at least account for the discussion

**Comment by jasmainak** [comment]
Any updates here? I am running some simulations and would love to play around with this feature using the GUI if it's available ...

**Comment by gtdang** [comment]
@jasmainak we haven't' started on this issue quite yet. I think a need for an API update was discussed in #635, which will need to be addressed before adding this GUI feature.

**Comment by kmilo9999** [comment]
@gtdang @gtdang I want to start working on my own PR instead of continuing #635 . I can take some notes and use some references from that PR in the new one.  Let me know your thoughts.

**Comment by ntolley** [comment]
@kmilo9999 I think it's safe to begin it from scratch, the GUI code has changed quite a lot since then making rebasing a huge pain for this one...
