### ISSUE TITLE
GUI synchronous Inputs

### ISSUE THREAD

**Issue by gtdang** [jonescompneurolab/hnn-core#716]
Ability to provide exogenous driving inputs synchronously.

**Comment by jasmainak** [comment]
This is literally just adding a checkbox and setting n_drive_cells = 1?

**Comment by gtdang** [comment]
> This is literally just adding a checkbox and setting n_drive_cells = 1?

I think `cell_specific=False` also needs to be set from what I see in the [ERP Tutorial](https://jonescompneurolab.github.io/hnn-core/stable/auto_examples/workflows/plot_simulate_evoked.html#sphx-glr-auto-examples-workflows-plot-simulate-evoked-py). 

Questions... 
* Can those values be edited on existing drives? Or should a new drive be added like in that tutorial example? 
* Should this setting only pertain to evoked drives? 
* Do we only need one checkbox/toggle for all drives? Or does each drive need its own toggle? 

@ntolley @rythorpe

**Comment by gtdang** [comment]
Discussed with @ntolley. 
* It would be cleaner to clear the drives and add new drives with the synchronous parameters because of gid ranges. 
* Should add for all types of drives not just evoked. 
* Each drive should have its own toggle.
