### ISSUE TITLE
GUI exporting simulations to csv

### ISSUE THREAD

**Issue by gtdang** [jonescompneurolab/hnn-core#718]
Add a button to export simulations to a csv file

- Simulations should have: time, L2, L5, and aggregate(L2 + L5) column.
- If multiple trials the file should be a wide format with L2, L5, and aggregate columns for each trial. 
- There should be a mean of trials set as well (L2, L5, and aggregate)

Related to #709

**Comment by kmilo9999** [comment]
@ntolley I wonder if you have pictured how this looks from the GUI side. ipywidgets (that a I know) doesn't have  a folder selector widget. I've been looking on creating a custom widget but it looks a bit more complicated that I initially thought.

**Comment by ntolley** [comment]
Honestly I assumed there would be one already built in. [This project](https://github.com/crahan/ipyfilechooser) seems to achieve what we want, but it's not great to add a uncommonly used/supported dependency for just one function.

**Comment by ntolley** [comment]
Alternatively could the[ `FileUpload`](https://github.com/jupyter-widgets/ipywidgets/blob/main/python/ipywidgets/ipywidgets/widgets/widget_upload.py) class source code by recycled for folder selection? I'll admit reading this it's a bit unclear if this is actually possible...

**Comment by jasmainak** [comment]
Why do you need a folder selector widget? To export multiple trials?

**Comment by jasmainak** [comment]
Try this:

```py
from ipywidgets import HTML
from IPython.display import display

import base64

res = 'computed results'

#FILE
filename = 'res.txt'
b64 = base64.b64encode(res.encode())
payload = b64.decode()

#BUTTONS
html_buttons = '''<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
<a download="{filename}" href="data:text/csv;base64,{payload}" download>
<button class="p-Widget jupyter-widgets jupyter-button widget-button mod-warning">Download File</button>
</a>
</body>
</html>
'''

html_button = html_buttons.format(payload=payload,filename=filename)
display(HTML(html_button))
```

probably what you're looking for

**Comment by kmilo9999** [comment]
@jasmainak Awesome! Thanks, you saved me a lot of time!
