### ISSUE TITLE
Remove unnecessary files from param folder

### ISSUE THREAD

**Issue by gtdang** [jonescompneurolab/hnn-core#724]
The param folder has params in HDF5 and json. Once the GUI tutorials are completed we there should be a review of all the parameter files used in all tutorials (GUI and API) and remove any unnecessary files. HDF5 files take up 1.3MB--while not huge, they are significantly larger than previous param files and can add up if more are eventually added.

**Comment by jasmainak** [comment]
If you added it already to git history ... no point in removing it later unless you intend to modify the original commit ...

**Comment by gtdang** [comment]
Hmm... I see. I suppose we could commit each file individually then. So we can revert the ones we don't want to keep. Or is it not really worth the effort to save a little bit of space?

**Comment by gtdang** [comment]
@ntolley @dylansdaniels Thoughts? Could be nice to not have the additional bloat with the package. Perhaps only have the default.hdf5 included with the package.

**Comment by dylansdaniels-berkeley** [comment]
@jasmainak's suggestion makes perfect sense to me, that's how I would approach it as well
