### ISSUE TITLE
GUI importing csv data files

### ISSUE THREAD

**Issue by gtdang** [jonescompneurolab/hnn-core#755]
Edit the data upload widget to support csv files generated by the GUI, introduced in #718. It currently accepts only tab delimited txt files with only 2 columns. 

**To Do:**
- [x] Add support for csv files. It will only load the agg column. 
- [ ] ~~Add support for selecting multiple files so multiple trials can be uploaded concurrently~~
- [ ] ~~If multiple files are uploaded, they should be plotted onto a single plot. It should not be plotted on individual plots/tabs.~~

**Comment by kmilo9999** [comment]
I think we did this in #753 . Can we close this issue ?

**Comment by gtdang** [comment]
#753 only addresses single-file correct? Maybe we can keep open for the multiple file implementation as a nice-to-have.

**Comment by gtdang** [comment]
Or we can close this and open up a new one for the multi-file implementation?

**Comment by gtdang** [comment]
Closing and moving multi-file loading as a separate issue.
