### ISSUE TITLE
API: Change add_tonic_bias argument structure

### ISSUE THREAD

**Issue by gtdang** [jonescompneurolab/hnn-core#764]
Update the Network `add_tonic_bias` method to accept a dictionary of cell types and amplitudes. As discussed in #635.

**Comment by ntolley** [comment]
Adding on to this issue, we should add a `name` parameter to this function. It's not unreasonable to add multiple tonic biases to the same cell. Many electrophysiology experiments have multiple stages to the "biases" added, for example hyperpolarizing all of the cells at the beginning, and then depolarizing immediately after.

**Comment by jasmainak** [comment]
@ntolley I think `net.biases` is a list rather than dictionary? How would we store the name?

**Comment by gtdang** [comment]
I think it's currently set like below. I believe it's a multi-level dict. Would it make the most sense to add a layer between "tonic" and "cell type"?  `self.external_biases['tonic'][<NAME>][cell_type]`. 

```python
self.external_biases['tonic'][cell_type] = {
            'amplitude': amplitude,
            't0': t0,
            'tstop': tstop
        }
```
