### ISSUE TITLE
Parallel Context as a mutually exclusive option to joblibs

### ISSUE THREAD

**Issue by blakecaldwell** [jonescompneurolab/hnn-core#78]
https://github.com/hnnsolver/hnn-core/blob/0aa973ef430e67e3266883e909ea02945d41a1ac/hnn_core/dipole.py#L27-L34

@jasmainak I'm preparing a PR to add ParallelContext (n_cores > 1, but not compatible with n_jobs > 1). A function similar to _clone_and_simulate will be called, and the net.* functions need to be part of it. Can you explain why these functions need to separate from Network(params, n_cores)? All of _clone_and_simulate gets pickled, right? Perhaps these net.* calls can be part of an appropriately named method of Network.

**Comment by blakecaldwell** [comment]
Re: pickling. I should have said the params to _clone_and_simulate get pickled, right? So separating these calls isn't related to pickling? Having these functions called inside dipole.py and from a Network() instantiation by the user sounds good to me and somewhat addresses my concern about calling NEURON multiple times to build the network. However, I'd like to add net._gid_assign() to the above list of calls? That would mean neuron doesn't get called at all with a Network() instantiation.

**Comment by jasmainak** [comment]
> I should have said the params to _clone_and_simulate get pickled, right? 

yep I think so, that's how it works

> So separating these calls isn't related to pickling?

umm ... no I don't think it's related to pickling. IIRC, I think it was because of some weird way Neuron was working. The pickling is just related to the fact that I pass a params dictionary and not a network object

> However, I'd like to add net._gid_assign() to the above list of calls? That would mean neuron doesn't get called at all with a Network() instantiation.

Oh yeah, that would be fantastic!

**Comment by jasmainak** [comment]
can this PR be closed? what remains to be done here @blakecaldwell ?

**Comment by blakecaldwell** [comment]
Agree that this can be closed.
