### ISSUE TITLE
Example Error like File not found error

### ISSUE THREAD

**Issue by hanbuck30** [jonescompneurolab/hnn-core#786]
![image](https://github.com/jonescompneurolab/hnn-core/assets/59501945/e4f92daf-1094-476d-b795-96a30e0f89ea)

![image](https://github.com/jonescompneurolab/hnn-core/assets/59501945/57502b35-f636-407e-87a9-dfc7f36f9ede)
I ran sample for the first time, and I get a file not found error. Even if I go into the mod folder, I don't have a .so or .dll file, where can I get it?

**Comment by jasmainak** [comment]
can you please provide more information how you did the installation and what kind of computer you have?

**Comment by hanbuck30** [comment]
I used the "git clone https://github.com/jonescompneurolab/hnn-core.git " command. And I'm using window 11, and I ran it on Vs code. Python version is 3.8 version and neurons are 8.2.
![image](https://github.com/jonescompneurolab/hnn-core/assets/59501945/e84b61c3-44f1-4fa3-8dec-7adf9adb3b68)

When I check the error, I check the error that requires .so or .dll in the mod folder, but when I check the git clone, I can't check the file in that format in mod

**Comment by jasmainak** [comment]
the mod files are built during installation using `nrniv` which is distributed using Neuron. You have to install neuron *before* installing HNN ... otherwise the mod files won't be built.

**Comment by hanbuck30** [comment]
![image](https://github.com/jonescompneurolab/hnn-core/assets/59501945/2862709f-b62b-47ca-afcd-68a6b5288df3)
I installed neuron before install HNN_core. but it still cause an same error

**Comment by hanbuck30** [comment]
Oh,  It works.  I think I forgot.
Thank you for your help.
One more question. I want to extract a code that encodes EEG data into a spoke, which file should I refer to?

**Comment by rythorpe** [comment]
I'd recommend checking out our examples page [here](https://jonescompneurolab.github.io/hnn-core/stable/auto_examples/index.html). There are a few examples where we simulate a current dipole (underlying an EEG sensor signal) and then examine the spiking activity that emerged within the network.

**Comment by rythorpe** [comment]
I'm going to close this issue, but feel free to post on the repository's Discussions forum with any more questions that arise.
