### ISSUE TITLE
HNN core fails with Python 3.12

### ISSUE THREAD

**Issue by kmilo9999** [jonescompneurolab/hnn-core#796]
Some test are failing with python 3.12

hnn_core/tests/test_drives.py FF.                                        [  8%]
hnn_core/tests/test_extracellular.py F....                               [ 12%]

        events_per_cycle = 5
        cycle_events_isi = 20
        with pytest.raises(ValueError,
                           match=r'Burst duration (?s).* cannot be greater than'):
>           _create_bursty_input(t0=t0, t0_stdev=t0_stdev,
                                 tstop=tstop, f_input=f_input,
                                 events_jitter_std=events_jitter_std,
                                 events_per_cycle=events_per_cycle,
                                 cycle_events_isi=cycle_events_isi,
                                 prng=prng, prng2=prng2)

hnn_core/tests/test_drives.py:80: 

https://github.com/jonescompneurolab/hnn-core/actions/runs/9489579191/job/26151176286

**Comment by jasmainak** [comment]
Fix welcome !
