### ISSUE TITLE
GUI - Load data first throws exception

### ISSUE THREAD

**Issue by kmilo9999** [jonescompneurolab/hnn-core#824]
It seems the dropdown list of simulated data to download it's including loaded data

Steps to replicate:
- Load data
- Run simulation
- Error printed in output console

**Comment by ntolley** [comment]
I chatted with @rythorpe and the original GUI did not allow exporting of data that was loaded in

**Comment by kmilo9999** [comment]
> I chatted with @rythorpe and the original GUI did not allow exporting of data that was loaded in

Thank you Nick. I'll proceed to fix this.
