### ISSUE TITLE
CI: Tests are running for very long after merging #673

### ISSUE THREAD

**Issue by gtdang** [jonescompneurolab/hnn-core#838]
After the merging of https://github.com/jonescompneurolab/hnn-core/pull/673, CI time for unit tests has gone up significantly.  This will slow down the speed feedback/development considerably. Can the tests be streamlined? 

**MacOS:** _11m_ -> _**34m**_
**Unbuntu:** _19m_ -> _**55m**_
**Windows:** _16m_ -> _**1h 43m**_

@ntolley @carolinafernandezp

**Comment by ntolley** [comment]
Oof that's on me, there's a few changes I can implement:
- restrict the maximum number of iterations
- simulate a smaller network
- increase dt

That should bring everything back to around the same runtime
