### ISSUE TITLE
GUI: RMSE not displaying when comparing user data against simulations with multiple trials

### ISSUE THREAD

**Issue by dylansdaniels** [jonescompneurolab/hnn-core#858]
We noticed that if you run a simulation with multiple trials, and then load in the user data for comparison, the RMSE is not displaying on the dipole graph. The fix here is that the GUI should use the average dipole for computing the RMSE.

**Comment by dylansdaniels** [comment]
@kmilo9999

**Comment by kmilo9999** [comment]
I noticed that in the comparison visualization if you select in the `Simulation data `dropdown the loaded data and in the `Data to compare` dropdown the muti-trial simulation, it does show the RMSE annotation.  The other way around the logic it throws an exception
`'Dipole at index 2 was already an average of 2 trials. Cannot reaverage'`

It happens in file `dipole.py` in the function  `average_dipoles(dpls)`

**Comment by ntolley** [comment]
I'm guessing a well placed `.copy()` might resolve this problem?

**Comment by kmilo9999** [comment]
Should the `simulation data `dropdown only have simulated data? It is listing both loaded and simulated.
![image](https://github.com/user-attachments/assets/80563f1b-2d48-4655-9a3a-7ae4166993d1)
If that's the case, what about changing the label of that widget?
