### ISSUE TITLE
GUI: Dipole not displaying after loading user data 

### ISSUE THREAD

**Issue by dylansdaniels** [jonescompneurolab/hnn-core#859]
I'm running into an issue where the dipole is not displaying when adding user data. It's hanging on a blank subplot without actually drawing the dipole/user data. I can force it to draw the correct output if I queue up another action for the figure; e.g., if I clear the histogram, the dipole is then drawn at that point. See the GIF below. I show multiple examples of how to trigger the behavior and force it to draw the dipole

![hnn_gui_dipole_not_displaying](https://github.com/user-attachments/assets/581737c3-8cc5-4ce3-8e0f-0f1de995a0b9)

The simulation is simply the default with 3 trials, and the 'data to compare' is 'yes_trial_S1_ERP_all_avg.txt' from the hnn data repository

**Comment by jasmainak** [comment]
cc @gtdang @kmilo9999 ... tagging them since they may not be watching the repo

**Comment by gtdang** [comment]
Seems like this happens only with simulations with multiple trials as well? Curious if fixing #858 will fix this one too...
