### ISSUE TITLE
MPIBackend platform logic

### ISSUE THREAD

**Issue by gtdang** [jonescompneurolab/hnn-core#875]
Was inspecting the MPIBackend class and found this logic below.

https://github.com/jonescompneurolab/hnn-core/blob/ccef332d3190a6a7338703c74641abd817d3056d/hnn_core/parallel_backends.py#L650-L655

Isn't this setting posix=True for Windows and Mac (Dar**win**), and False for Linux? [sys.platform docs](https://docs.python.org/3/library/sys.html#sys.platform)

Although somehow MPI seems to be working OK on Linux despite the incorrect flag here?

**Comment by rythorpe** [comment]
Maybe I'm missing something here, but don't we want `posix=True` only for Windows? If so, the Linux flag is correct as-is.

**Comment by gtdang** [comment]
posix is Unix style, you’d want it True for Mac and Linux.  The shlex.split function defaults with True, you only want to pass it posix=False for Windows so it can parse backslashes correctly.  See the test examples above.

**Comment by rythorpe** [comment]
Oh I get it now. It's a good thing I asked because I had that all mixed up in my head 🙃 Thanks @gtdang!
