### ISSUE TITLE
API: Synaptic gains

### ISSUE THREAD

**Issue by gtdang** [jonescompneurolab/hnn-core#885]

**Comment by gtdang** [comment]
@ntolley 
Can we discuss what is needed for this issue?

**Comment by ntolley** [comment]
@gtdang yes this slipped through the cracks!

Synaptic gains means that connection weights between neurons are multiplied by some scalar gain factor. There will be four values:
E-E, E-I, I-E, I-I

The "E cells" are L2 and L5 pyramidal neurons

The "I cells" are L2 and L5 basket neurons

Setting E-E to `2.0` would mean you double the weight of all connections where the source and target are both pyramidal neurons.

**Comment by gtdang** [comment]
Ah ok. So for the GUI would those 4 constants be set in one location and they are applied to any applicable connection? Or does the gain need to be adjusted for each individual connection? 

In other words, should the gain widgets be outside (1) or inside (2) the connection accordion boxes? 
![Screenshot 2024-09-10 at 3 01 21 PM](https://github.com/user-attachments/assets/ce6f5f91-40ad-41f7-89ac-554e5829db6b)

**Comment by jasmainak** [comment]
I would implement these functions in HNN-core and then just add the sliders in the GUI. That way, it can be used in both interfaces

**Comment by gtdang** [comment]
Oh, has gain adjustment not been implemented in the api?

**Comment by ntolley** [comment]
Potential API?

```py
net.synaptic_gains(EE=None, EI=None, II=None, IE=None)
```

And it just updates attributes of the same name like `net._EE` etc.?

**Comment by jasmainak** [comment]
I would make the default 1 instead of None :) Do we need to track the gain factor or it's already stored in the weights of the connectivity?

**Comment by jasmainak** [comment]
okay let's implement it, then example code will make it clear what's the best way forward !

**Comment by gtdang** [comment]
So at one point does the gain get applied? At simulation?

**Comment by jasmainak** [comment]
My personal preference is to just do:

```py
net.copy().update_weights(EE=1., EI=2., II=1., IE=1.)
```

to keep our codebase clean.
