### ISSUE TITLE
extracting spike times by cell type

### ISSUE THREAD

**Issue by jasmainak** [jonescompneurolab/hnn-core#912]
I want to make a nicer version of the histogram plot for my work using [KernelDensity](https://scikit-learn.org/dev/modules/generated/sklearn.neighbors.KernelDensity.html)

However, the `cell_response` object does not store the information of spikes for each cell type. I have:

```py
cell_response._spike_times
cell_response._spike_types
```

I guess the dictionary of spike times per cell type is assembled in the `cell_response.plot_spikes_hist` but it's never exposed to the user. Can we expose this to the user somehow?

**Comment by ntolley** [comment]
It's a good suggestion, the devil is in figuring out a non-redundant name for this variable

```py
cell_response.spike_dict
cell_response.spike_map
cell_response.spike_lookup
```

I'll admit I'm not happy with any of these...
